// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/consulto/ConsultView.tsx": () => import("../components/mockups/consulto/ConsultView.tsx"),
  "./components/mockups/consulto/SharePanel.tsx": () => import("../components/mockups/consulto/SharePanel.tsx")
};
