export const REFERRAL_REASONS = [
  { key: "artralgie",     label: "Artralgie / sospetta artrite infiammatoria" },
  { key: "fibromialgia",  label: "Dolore diffuso / sospetta fibromialgia" },
  { key: "osteoporosi",   label: "Osteoporosi / frattura da fragilità / MOC" },
  { key: "autoanticorpi", label: "Autoanticorpi positivi isolati" },
  { key: "connettivite",  label: "Sospetta connettivite / malattia sistemica" },
  { key: "pmr_lvv",       label: "Sospetta PMR / GCA / LVV" },
  { key: "spa",           label: "Lombalgia infiammatoria / sospetta SpA" },
  { key: "altro",         label: "Altro / motivo non specificato" },
];

export const FRAILTY_ITEMS = [
  "Cadute ricorrenti","Ridotta mobilità / allettamento","Deterioramento cognitivo",
  "Polifarmacia (≥5 farmaci)","Scarsa aderenza terapeutica","Assenza caregiver",
  "Difficoltà sociali / lavorative","Malnutrizione / cachessia","Isolamento sociale",
];

export const CHECKLISTS = {
  artralgie: {
    clinical: [
      { key: "morning_stiffness", label: "Rigidità mattutina >1 ora" },
      { key: "joint_swelling",    label: "Tumefazione articolare obiettivabile" },
      { key: "symmetric",         label: "Distribuzione simmetrica" },
      { key: "small_joints",      label: "Coinvolgimento piccole articolazioni (mani/piedi)" },
      { key: "axial",             label: "Coinvolgimento assiale" },
      { key: "extra_articular",   label: "Manifestazioni extra-articolari (cute, occhi, mucose)" },
      { key: "family_history",    label: "Familiarità per AR o artrite infiammatoria" },
      { key: "recent_infection",  label: "Infezione recente precedente all'artrite" },
      { key: "psoriasis",         label: "Psoriasi cutanea o ungueale" },
      { key: "ibd",               label: "Malattia infiammatoria intestinale" },
    ],
    red_flags: [
      { key: "fever_arthritis", label: "Artrite + febbre alta (>38.5°C)" },
      { key: "monoarthritis",   label: "Monoartrite acuta (escludere settica/gotta)" },
      { key: "septic_risk",     label: "Fattori di rischio per artrite settica" },
    ],
    labs: ["FR","Anti-CCP","ANA","ENA panel","VES","PCR","Emocromo","Uricemia","Creatinina","LFT","Liquido sinoviale (se disponibile)"],
    imaging: ["Ecografia articolare","Rx mani e polsi","Rx piedi","RMN mani (se eco neg.)","Scintigrafia ossea"],
    diagnoses: ["Artrite reumatoide","Artrite psoriasica","SpA periferico","Artrite reattiva","Gotta / microcristalli","Artrite virale","Osteoartrosi erosiva","Connettivite con artrite","Artrite indifferenziata"],
  },
  fibromialgia: {
    clinical: [
      { key: "diffuse_pain_3m",   label: "Dolore diffuso da >3 mesi" },
      { key: "tender_points",     label: ">11/18 tender points positivi" },
      { key: "sleep_disorder",    label: "Disturbi del sonno / sonno non ristoratore" },
      { key: "fatigue",           label: "Fatica cronica importante" },
      { key: "headache",          label: "Cefalea tensiva o emicrania" },
      { key: "ibs",               label: "Sindrome del colon irritabile" },
      { key: "allodynia",         label: "Allodinia / ipersensibilità al tatto" },
      { key: "cognitive_fog",     label: "Nebbiosità cognitiva (fibro-fog)" },
      { key: "anxiety_depression",label: "Ansia / depressione associata" },
    ],
    red_flags: [
      { key: "weight_loss",             label: "Calo ponderale involontario" },
      { key: "night_sweats",            label: "Sudorazione notturna" },
      { key: "fever",                   label: "Febbre non spiegata" },
      { key: "lymphadenopathy",         label: "Linfoadenopatie" },
      { key: "very_high_esr",           label: "VES molto elevata (>50 mm/h)" },
      { key: "objective_joint_findings",label: "Tumefazione articolare obiettivabile" },
    ],
    labs: ["VES","PCR","ANA","TSH","CPK","Vitamina D","Emocromo","Glicemia","Ferritina"],
    imaging: ["Rx colonna (se dolore assiale)","RMN colonna (se neuralgia irradiata)"],
    diagnoses: ["Fibromialgia","Sindrome da sensibilizzazione centrale","Ipotiroidismo sintomatico","Depressione somatizzante","Spondiloartrosi sintomatica"],
  },
  osteoporosi: {
    clinical: [
      { key: "fragility_fracture",  label: "Frattura da fragilità (vertebrale, femore, polso)" },
      { key: "height_loss",         label: "Perdita di statura >4 cm" },
      { key: "dorsal_kyphosis",     label: "Cifosi dorsale ingravescente" },
      { key: "early_menopause",     label: "Menopausa precoce (<45 anni)" },
      { key: "prolonged_steroids",  label: "Uso cronico di corticosteroidi (>3 mesi)" },
      { key: "hypogonadism",        label: "Ipogonadismo maschile" },
      { key: "malabsorption",       label: "Malassorbimento / celiachia" },
      { key: "family_osteoporosis", label: "Familiarità per osteoporosi o frattura femore" },
      { key: "smoking_alcohol",     label: "Fumo attivo / abuso alcolico" },
      { key: "low_bmi",             label: "BMI <18.5" },
    ],
    red_flags: [
      { key: "vertebral_no_trauma",label: "Frattura vertebrale senza trauma (mieloma?)" },
      { key: "bone_pain",          label: "Dolore osseo persistente non spiegato" },
      { key: "hypercalcemia",      label: "Ipercalcemia" },
    ],
    labs: ["Calcio","Fosforo","Vitamina D","PTH","Creatinina","Fosfatasi alcalina","TSH","Testosterone/estradiolo","Proteinuria 24h","Bence Jones urinario","Emocromo"],
    imaging: ["MOC DEXA (colonna + femore)","Rx colonna T-L (crolli vertebrali)","Scintigrafia ossea (se dolore osseo)"],
    diagnoses: ["Osteoporosi post-menopausale","Osteoporosi da steroidi","Osteoporosi maschile","Osteoporosi secondaria","Osteopenia","Osteomalacia"],
  },
  autoanticorpi: {
    clinical: [
      { key: "ana_positive",   label: "ANA positivi (indicare titolo e pattern)" },
      { key: "ena_positive",   label: "ENA positivi (specificare anticorpo)" },
      { key: "anti_dsdna",     label: "Anti-dsDNA positivi" },
      { key: "anca_positive",  label: "ANCA positivi (MPO o PR3)" },
      { key: "apl_positive",   label: "Anticorpi antifosfolipidi (aCL, anti-B2GPI, LAC)" },
      { key: "rf_ccp",         label: "FR e/o anti-CCP positivi" },
      { key: "asymptomatic",   label: "Paziente attualmente asintomatico" },
      { key: "systemic_sx",    label: "Sintomi sistemici (artralgie, fatica, fotosensibilità)" },
    ],
    red_flags: [
      { key: "serositis",  label: "Sierosite (pleurite, pericardite)" },
      { key: "nephritis",  label: "Nefrite / proteinuria / ematuria" },
      { key: "cytopenia",  label: "Citopenia (anemia emolitica, leucopenia, piastrinopenia)" },
      { key: "fever",      label: "Febbre non spiegata" },
      { key: "rash",       label: "Rash cutaneo (malare, fotosensibile)" },
    ],
    labs: ["ANA titolo e pattern","ENA completo","Anti-dsDNA","Complemento (C3, C4, CH50)","Emocromo con formula","Creatinina","Proteinuria","ANCA","aCL / anti-B2GPI / LAC"],
    imaging: ["Eco addome","TC torace HRCT (ILD)","Ecocardio (se APL+ o sierosite)"],
    diagnoses: ["LES o overlap lupico","Sindrome di Sjögren","Sclerosi sistemica precoce","MCTD","Sindrome da anticorpi antifosfolipidi","AR sieropositiva","UCTD","Autoanticorpi senza malattia (follow-up)"],
  },
  connettivite: {
    clinical: [
      { key: "photosensitivity", label: "Fotosensibilità cutanea" },
      { key: "malar_rash",       label: "Rash malare a farfalla" },
      { key: "alopecia",         label: "Alopecia" },
      { key: "oral_ulcers",      label: "Ulcere orali ricorrenti" },
      { key: "raynaud",          label: "Fenomeno di Raynaud" },
      { key: "sicca",            label: "Xeroftalmia / xerostomia (sindrome sicca)" },
      { key: "myositis",         label: "Debolezza muscolare / miosite" },
      { key: "dysphagia",        label: "Disfagia / dismotilità esofagea" },
      { key: "sclerodactyly",    label: "Sclerodattilia / cute indurita" },
      { key: "telangiectasias",  label: "Teleangectasie" },
      { key: "arthritis",        label: "Artrite / artralgie" },
      { key: "serositis",        label: "Sierosite (pleurite/pericardite)" },
    ],
    red_flags: [
      { key: "lupus_nephritis",  label: "Nefrite lupica (proteinuria >0.5g, ematuria)" },
      { key: "severe_cytopenia", label: "Citopenia severa" },
      { key: "pah",              label: "Dispnea ingravescente (PAH?)" },
      { key: "ild_rapid",        label: "ILD rapidamente progressiva" },
    ],
    labs: ["ANA titolo/pattern","ENA completo (SSA, SSB, Sm, RNP, Scl-70, Jo-1)","Anti-dsDNA","Complemento","Emocromo","CPK","Creatinina","Proteinuria 24h"],
    imaging: ["Capillaroscopia nailfold","TC torace HRCT","Eco parotidi/ghiandole salivari","Ecocardio","Manometria esofagea"],
    diagnoses: ["LES","Sindrome di Sjögren primitiva","Sclerosi sistemica","MCTD","Miosite infiammatoria (DM/PM/IMNM)","Overlap syndrome","UCTD"],
  },
  pmr_lvv: {
    clinical: [
      { key: "age_over_50",        label: "Età >50 anni" },
      { key: "shoulder_stiffness", label: "Rigidità/dolore cingolo scapolare" },
      { key: "hip_stiffness",      label: "Rigidità/dolore cingolo pelvico" },
      { key: "morning_stiffness",  label: "Rigidità mattutina >45 minuti" },
      { key: "temporal_headache",  label: "Cefalea temporale o frontale" },
      { key: "jaw_claudication",   label: "Claudicatio mandibolare" },
      { key: "visual_symptoms",    label: "Diplopia / calo visivo / amaurosi fugace" },
      { key: "scalp_tenderness",   label: "Dolorabilità cuoio capelluto" },
      { key: "systemic_symptoms",  label: "Febbre, calo ponderale, astenia" },
      { key: "high_esr",           label: "VES >50 mm/h" },
      { key: "limb_claudication",  label: "Claudicatio degli arti (LVV/Takayasu)" },
      { key: "asymmetric_pulses",  label: "Differenza pressoria tra arti / soffi vascolari" },
    ],
    red_flags: [
      { key: "visual_loss",        label: "URGENZA: perdita visiva acuta (GCA oculare)" },
      { key: "jaw_claudication_u", label: "URGENZA: claudicatio mandibolare severa" },
      { key: "tia_stroke",         label: "URGENZA: TIA o ictus in corso" },
    ],
    labs: ["VES","PCR","Emocromo","LFT","Ferritina","IL-6 (se disponibile)","Creatinina"],
    imaging: ["Eco Doppler TSA (halo sign)","Eco spalle e anche (borsiti)","PET/CT (se LVV sospetta)","TC torace/addome (se LVV)","Biopsia arteria temporale (se GCA)"],
    diagnoses: ["PMR (Polimialgia Reumatica)","GCA (Arterite a Cellule Giganti)","LVV / Arterite di Takayasu","PMR overlap GCA","PMR secondaria (escludere neoplasia)"],
  },
  spa: {
    clinical: [
      { key: "age_under_45",        label: "Età di esordio <45 anni" },
      { key: "chronic_back_3m",     label: "Lombalgia cronica >3 mesi" },
      { key: "better_activity",     label: "Miglioramento con attività, peggioramento a riposo" },
      { key: "morning_stiffness",   label: "Rigidità mattutina >30 minuti" },
      { key: "alternating_buttock", label: "Dolore gluteo alternante" },
      { key: "night_awakening",     label: "Risveglio notturno nella seconda metà della notte" },
      { key: "uveitis",             label: "Uveite anteriore (attuale o pregressa)" },
      { key: "psoriasis",           label: "Psoriasi cutanea o ungueale" },
      { key: "ibd",                 label: "IBD (Crohn o RCU)" },
      { key: "enthesitis",          label: "Entesiti periferiche (tallone, rotuleo)" },
      { key: "dactylitis",          label: "Dattilite (dito a salsicciotto)" },
      { key: "family_hla_b27",      label: "Familiarità per SpA / HLA-B27+" },
    ],
    red_flags: [
      { key: "weight_loss",       label: "Calo ponderale" },
      { key: "fever",             label: "Febbre" },
      { key: "late_onset",        label: "Esordio dopo i 50 anni (escludere altre cause)" },
      { key: "bilateral_sciatica",label: "Sciatica bilaterale" },
    ],
    labs: ["HLA-B27","VES","PCR","Emocromo","Creatinina","ANA (se overlap sospetto)"],
    imaging: ["Rx sacroiliache (proiezione Ferguson)","RMN sacroiliache (STIR + T1)","Rx colonna lombare","Eco entesiti periferiche"],
    diagnoses: ["SpA assiale radiografica (AS)","SpA assiale non-radiografica (nr-axSpA)","SpA periferico / artrite psoriasica","Spondiloartrosi degenerativa (escludere SpA)"],
  },
  altro: {
    clinical: [], red_flags: [], labs: [], imaging: [],
    diagnoses: ["Da definire"],
  },
};

export const RHEUM_TEMPLATES = {
  artralgie: "Artralgie a carico di [specificare articolazioni] da circa [durata]. Rigidità mattutina della durata di [___] minuti. [Presenza/assenza di tumefazione articolare obiettivabile]. [Episodi precedenti e decorso]. [Terapie FANS o corticosteroidi assunte e risposta clinica]. Nessuna precedente diagnosi reumatologica documentata.",
  fibromialgia: "Dolore diffuso di intensità [VAS 0-10] da circa [durata]. Disturbi del sonno: [specificare]. Fatica cronica: [presente/assente]. [Evento precipitante identificabile: trauma, evento stressante, infezione?]. [Precedenti valutazioni specialistiche]. Assenza di diagnosi reumatologica precedentemente documentata.",
  autoanticorpi: "Riscontro di [specificare autoanticorpi] in data [data], titolo [specificare]. Contesto: [occasionale/screening/sintomi]. Paziente [asintomatico/sintomatico]. [Manifestazioni presenti: specificare]. [Storia familiare per malattie autoimmuni]. Nessuna diagnosi reumatologica precedentemente documentata.",
  connettivite: "Sintomi presenti da circa [durata]: [elencare sintomi principali in ordine cronologico]. [Storia familiare per connettivite o malattie autoimmuni]. [Precedenti valutazioni specialistiche o diagnosi]. [Terapie immunosoppressive o corticosteroidi già assunti].",
  pmr_lvv: "Comparsa di dolenzia/rigidità ai cingoli [scapolare / pelvico / entrambi] da circa [durata]. Rigidità mattutina di [___] minuti. Sintomi sistemici: [febbre / calo ponderale / astenia]. [Cefalea temporale o frontale]. [Sintomi visivi o vascolari]. VES [___] e PCR [___] alla prima valutazione.",
  spa: "Lombalgia infiammatoria da circa [durata], con esordio all'età di [___] anni. Rigidità mattutina di [___] minuti, con miglioramento con l'attività fisica. [Episodi di dolore gluteo alternante]. [Risveglio notturno nella seconda metà della notte]. Manifestazioni extra-muscoloscheletriche: [uveite / psoriasi / IBD / entesiti]. HLA-B27: [positivo / negativo / non noto]. [Precedenti valutazioni o diagnosi].",
  altro: "[Descrivere la storia clinica rilevante: durata dei sintomi, loro evoluzione, terapie già intraprese, precedenti valutazioni specialistiche].",
};

export const BONE_TEMPLATE = "Menopausa a [___] anni, [naturale / chirurgica / farmacologica]. [Numero di gravidanze e allattamenti]. Fratture da fragilità pregresse: [nessuna / specificare sede e anno]. MOC DEXA precedenti: [nessuna / T-score colonna ___ femore ___ anno ___]. Terapie per osteoporosi pregresse: [nessuna / specificare: bifosfonati, denosumab, teriparatide, ecc.]. Supplementazione con calcio e vitamina D: [sì / no]. Attività fisica abituale: [sedentaria / moderata / regolare]. Fumo: [no / sì, ___ sigarette/die]. Alcol: [no / sì, ___ unità/settimana].";

export const EXAM_TEMPLATES = {
  artralgie: "Condizioni generali: [buone/discrete/scadenti]. Cute e mucose: [normali / specificare].\nArticolazioni:\n- Mani/polsi: [tumefazione / dolorabilità a ___; oppure nella norma]\n- Piedi/caviglie: [___]\n- Grandi articolazioni: [___]\nArticolazioni dolenti (TJC28): [n]. Articolazioni tumefate (SJC28): [n].\nForza muscolare: [conservata].\nEO internistico: [nella norma / specificare].",
  fibromialgia: "Condizioni generali: [buone/discrete].\nTender points: [n]/18 positivi.\nArticolazioni: nessuna tumefazione obiettivabile. Dolorabilità diffusa alla pressione superficiale dei punti diagnostici.\nForza muscolare: conservata.\nCute e mucose: nella norma.\nEO internistico: nella norma.",
  osteoporosi: "Condizioni generali: [buone/discrete/scadenti]. Altezza attuale: [___] cm. Peso: [___] kg. BMI: [___].\nColonna vertebrale: [cifosi dorsale assente/presente]. Dolore alla percussione vertebrale: [assente / presente a livello ___].\nArticolazioni: [nella norma / ___].\nForza muscolare: [conservata / ridotta].\nEO internistico: nella norma.",
  autoanticorpi: "Condizioni generali: [buone/discrete].\nCute: [normale / rash ___ / noduli]. Mucose: [normali / ulcere orali]. Capelli: [normali / alopecia].\nFenomeno di Raynaud: [non evidenziabile / riferito dal paziente].\nArticolazioni: [nessuna tumefazione / ___].\nCapillaroscopia: [non eseguita / pattern ___].\nEO internistico: nella norma.",
  connettivite: "Condizioni generali: [buone/discrete].\nCute: [normale / rash malare / sclerodattilia / teleangectasie / ___]. Mucose: [normali / ulcere orali / xerostomia]. Capelli: [normali / alopecia].\nCapillaroscopia nailfold: [non eseguita / pattern ___ ].\nFenomeno di Raynaud: [non evidenziabile / presente].\nArticolazioni: [___]. Forza muscolare prossimale: [conservata / ridotta (___/5)].\nEO internistico: [nella norma / specificare].",
  pmr_lvv: "Condizioni generali: [buone/discrete/compromesse].\nArterie temporali: [pulsanti, non ispessite, non dolenti / ispessite / dolorabili a ___].\nCingolo scapolare: mobilità [conservata / limitata], dolore alla mobilizzazione passiva [assente / presente].\nCingolo pelvico: mobilità [conservata / limitata], dolore [assente / presente].\nArticolazioni periferiche: [nessuna tumefazione / ___].\nPressione arteriosa: [dx ___ / sin ___]. Polsi: [presenti e simmetrici / differenza ___].\nEO internistico: [nella norma / specificare].",
  spa: "Condizioni generali: [buone/discrete].\nColonna lombare:\n- Schober modificato: [___/15 cm]\n- Distanza dito-pavimento: [___] cm\n- Espansione toracica: [___] cm\nArticolazioni sacroiliache: manovre di provocazione [negative / positive a dx / sn / bilateralmente].\nEntesi: [nessuna dolorabilità / tender a: tallone / rotuleo / altro ___].\nArticolazioni periferiche: [nessuna tumefazione / ___].\nCute e mucose: [normali / psoriasi a ___].\nEO internistico: nella norma.",
  altro: "Condizioni generali: [buone/discrete/scadenti].\nCute e mucose: [___].\nArticolazioni: [___].\nForza muscolare: [___].\nEO internistico: [___].",
};

export const FOLLOW_UP_PRIORITY = [
  { key: "urgent",   label: "Urgente (<4 settimane)",    color: "bg-red-100 border-red-300 text-red-800" },
  { key: "priority", label: "Prioritario (1–3 mesi)",    color: "bg-amber-100 border-amber-300 text-amber-800" },
  { key: "routine",  label: "Routine (>3 mesi)",         color: "bg-blue-100 border-blue-300 text-blue-800" },
  { key: "none",     label: "Non necessario / conclude", color: "bg-gray-100 border-gray-200 text-gray-600" },
];

export const HYPOTHESIS_TO_DISEASE = {
  "Artrite reumatoide":  "ra",
  "Artrite psoriasica":  "psa",
  "SpA assiale":         "spa",
  "SpA periferico":      "spa",
  "LES":                 "sle",
  "Sindrome di Sjögren": "sjogren",
  "Sclerosi sistemica":  "sclero",
  "PMR / GCA":           "pmr",
};

export const DEFINITIVE_DIAGNOSES = [
  { label: "Artrite reumatoide",      profileKey: "ra" },
  { label: "Artrite psoriasica",      profileKey: "psa" },
  { label: "SpA assiale",             profileKey: "spa" },
  { label: "SpA periferico",          profileKey: "spa" },
  { label: "LES",                     profileKey: "sle" },
  { label: "Sindrome di Sjögren",     profileKey: "sjogren" },
  { label: "Sclerosi sistemica",      profileKey: "sclero" },
  { label: "PMR / GCA",              profileKey: "pmr" },
  { label: "Miosite",                 profileKey: "myositis" },
  { label: "Vasculite ANCA",          profileKey: "aav" },
  { label: "MCTD / Connettivite",     profileKey: null },
  { label: "UCTD",                    profileKey: null },
  { label: "Gotta / microcristalli",  profileKey: null },
  { label: "Artrosi",                 profileKey: null },
  { label: "Osteoporosi",             profileKey: null },
  { label: "Fibromialgia",            profileKey: null },
  { label: "Artrite indifferenziata", profileKey: null },
  { label: "Altra malattia reumatica",          profileKey: null },
  { label: "Nessuna malattia reumatologica",    profileKey: null },
];

export const NEXT_STEP_OPTIONS = [
  { key: "rheumatology",      label: "Follow-up reumatologico" },
  { key: "urgent",            label: "Invio urgente / ricovero" },
  { key: "gp",                label: "Ritorno al MMG" },
  { key: "specialist",        label: "Consulenza altra specialità" },
  { key: "multidisciplinary", label: "Percorso multidisciplinare" },
];

export const CERTAINTY_OPTIONS = [
  { key: "confirmed",    label: "Diagnosi confermata",   color: "bg-green-100 border-green-300 text-green-800" },
  { key: "suspected",   label: "Diagnosi sospettata",   color: "bg-blue-100 border-blue-300 text-blue-800" },
  { key: "excluded",    label: "Diagnosi esclusa",       color: "bg-gray-100 border-gray-200 text-gray-500" },
  { key: "undetermined",label: "In valutazione",         color: "bg-amber-100 border-amber-300 text-amber-800" },
];

export const REFERRAL_APPROPRIATENESS = [
  { key: "appropriate",   label: "Appropriata" },
  { key: "borderline",    label: "Borderline" },
  { key: "inappropriate", label: "Non appropriata" },
];

export const EMPTY_DATA = {
  referral_reason: null,
  referral_date: new Date().toISOString().slice(0, 10),
  clinical_question: "",
  referral_source: "",
  comorbidities: {},
  comorbidity_item_notes: {},
  comorbidity_free_notes: "",
  drug_allergies: "",
  surgical_history: "",
  frailty: [],
  current_therapies_text: "",
  previous_therapies_text: "",
  rheumatologic_history: "",
  bone_history: "",
  family_history: "",
  physiologic_history: "",
  physical_exam: "",
  physical_exam_joint_exam: {},
  physical_exam_systems: {},
  physical_exam_mrss: {},
  physical_exam_pasi: {},
  physical_exam_lei: {},
  provisional_diagnosis: "",
  labs_imaging: "",
  clinical_features: {},
  red_flags: [],
  labs_ordered: [],
  labs_notes: "",
  imaging_ordered: [],
  imaging_notes: "",
  free_checklist_notes: "",
  diagnostic_conclusion: "",
  diagnostic_certainty: null,
  suggested_diagnosis: "",
  referral_appropriateness: null,
  next_step: null,
  follow_up_priority: null,
  requested_tests: [],
  requested_tests_notes: "",
  outcome_notes: "",
  therapy_modification: "",
  confirmed_diagnosis: "",
  clinical_decision: "open",
  follow_up_date: "",
};
