// Pannelli di esami laboratorio reumatologico predefiniti
// Chiavi DEVONO corrispondere ai param.key di labValueExtractor.js

export const LAB_PANELS = {
  emocromo: {
    label: "Emocromo",
    tests: [
      { key: "hb",           label: "Emoglobina",  unit: "g/dL",    type: "number", refMin: 12, refMax: 17 },
      { key: "mcv",          label: "MCV",          unit: "fL",      type: "number", refMin: 80, refMax: 100 },
      { key: "wbc",          label: "Leucociti",    unit: "x10⁹/L",  type: "number", refMin: 4,  refMax: 10 },
      { key: "neutrophils",  label: "Neutrofili",   unit: "x10⁹/L",  type: "number" },
      { key: "lymphocytes",  label: "Linfociti",    unit: "x10⁹/L",  type: "number" },
      { key: "eosinophils",  label: "Eosinofili",   unit: "x10⁹/L",  type: "number" },
      { key: "monocytes",    label: "Monociti",     unit: "x10⁹/L",  type: "number" },
      { key: "plt",          label: "Piastrine",    unit: "x10⁹/L",  type: "number", refMin: 150, refMax: 450 },
    ],
  },
  fase_acuta: {
    label: "Fase acuta",
    tests: [
      { key: "ves",          label: "VES",              unit: "mm/h",  type: "number", refMax: 30 },
      { key: "crp",          label: "PCR",              unit: "mg/dL", type: "number", refMax: 0.5 },
      { key: "fibrinogeno",  label: "Fibrinogeno",      unit: "mg/dL", type: "number", refMin: 200, refMax: 400 },
      { key: "ferritin",     label: "Ferritina",        unit: "ng/mL", type: "number" },
      { key: "saa",          label: "SAA (Amiloide A)", unit: "mg/L",  type: "number" },
    ],
  },
  funzione: {
    label: "Funzione organi / chimica",
    tests: [
      { key: "creatinine",      label: "Creatinina",        unit: "mg/dL",          type: "number", refMax: 1.2 },
      { key: "egfr",            label: "eGFR (CKD-EPI)",    unit: "mL/min/1.73m²",  type: "number" },
      { key: "ast",             label: "AST (GOT)",          unit: "U/L",            type: "number", refMax: 40 },
      { key: "alt",             label: "ALT (GPT)",          unit: "U/L",            type: "number", refMax: 40 },
      { key: "ggt",             label: "GGT",                unit: "U/L",            type: "number", refMax: 60 },
      { key: "ldh",             label: "LDH",                unit: "U/L",            type: "number" },
      { key: "ck",              label: "CPK / CK",           unit: "U/L",            type: "number", refMax: 200 },
      { key: "aldolase",        label: "Aldolasi",           unit: "U/L",            type: "number" },
      { key: "mioglobina",      label: "Mioglobina",         unit: "ng/mL",          type: "number" },
      { key: "urato",           label: "Acido urico",        unit: "mg/dL",          type: "number", refMax: 7 },
      { key: "vitd",            label: "25-OH Vitamina D",   unit: "ng/mL",          type: "number", refMin: 30 },
      { key: "albumin",         label: "Albumina",           unit: "g/dL",           type: "number", refMin: 3.5, refMax: 5.0 },
      { key: "proteine_totali", label: "Proteine totali",    unit: "g/dL",           type: "number", refMin: 6.0, refMax: 8.3 },
      { key: "antithrombin",    label: "Antitrombina III",   unit: "%",              type: "number", refMin: 80, refMax: 120 },
      { key: "inr",             label: "INR / PT ratio",     unit: "",               type: "number", refMin: 0.9, refMax: 1.2 },
    ],
  },
  lipidi: {
    label: "Lipidi",
    tests: [
      { key: "cholesterol_total", label: "Colesterolo totale", unit: "mg/dL", type: "number", refMax: 200 },
      { key: "hdl",               label: "HDL",                unit: "mg/dL", type: "number", refMin: 40  },
      { key: "ldl",               label: "LDL",                unit: "mg/dL", type: "number", refMax: 130 },
      { key: "triglycerides",     label: "Trigliceridi",       unit: "mg/dL", type: "number", refMax: 150 },
    ],
  },
  elettroforesi: {
    label: "Elettroforesi proteica",
    tests: [
      { key: "albumina_pct", label: "Albumina",       unit: "%",  type: "number", refMin: 55, refMax: 68 },
      { key: "alfa1_glob",   label: "α1-globuline",   unit: "%",  type: "number", refMin: 1,  refMax: 5 },
      { key: "alfa2_glob",   label: "α2-globuline",   unit: "%",  type: "number", refMin: 7,  refMax: 12 },
      { key: "beta1_glob",   label: "β1-globuline",   unit: "%",  type: "number" },
      { key: "beta2_glob",   label: "β2-globuline",   unit: "%",  type: "number" },
      { key: "gamma_glob",   label: "γ-globuline",    unit: "%",  type: "number", refMin: 11, refMax: 22 },
    ],
  },
  complemento: {
    label: "Complemento",
    tests: [
      { key: "c3",   label: "C3",   unit: "mg/dL", type: "number", refMin: 90,  refMax: 180 },
      { key: "c4",   label: "C4",   unit: "mg/dL", type: "number", refMin: 10,  refMax: 40 },
      { key: "c1q",  label: "C1q",  unit: "mg/dL", type: "number", refMin: 14,  refMax: 30 },
      { key: "ch50", label: "CH50", unit: "U/mL",  type: "number", refMin: 60,  refMax: 144 },
    ],
  },
  metabolismo_osseo: {
    label: "Metabolismo osseo",
    tests: [
      { key: "bap", label: "Fosfatasi alcalina ossea (BAP)", unit: "U/L",   type: "number", refMax: 43 },
      { key: "ctx", label: "CrossLaps / β-CTX",             unit: "ng/mL", type: "number", refMax: 0.57 },
    ],
  },
  marziale: {
    label: "Metabolismo del ferro",
    tests: [
      { key: "iron",                    label: "Sideremia",                  unit: "μg/dL",  type: "number", refMin: 60,  refMax: 170 },
      { key: "transferrina",            label: "Transferrina",               unit: "mg/dL",  type: "number", refMin: 200, refMax: 360 },
      { key: "saturazione_transferrina",label: "Saturazione transferrina",   unit: "%",      type: "number", refMin: 16,  refMax: 45  },
    ],
  },
  immunoglobuline: {
    label: "Immunoglobuline",
    tests: [
      { key: "igg",           label: "IgG",           unit: "mg/dL", type: "number", refMin: 700,  refMax: 1600 },
      { key: "iga",           label: "IgA",           unit: "mg/dL", type: "number", refMin: 70,   refMax: 400  },
      { key: "igm",           label: "IgM",           unit: "mg/dL", type: "number", refMin: 40,   refMax: 230  },
      { key: "crioglobuline", label: "Crioglobuline", unit: "",      type: "qual" },
    ],
  },
  autoanticorpi: {
    label: "Autoanticorpi",
    tests: [
      { key: "fr",            label: "Fattore Reumatoide (FR)",      unit: "UI/mL",  type: "number", refMax: 14 },
      { key: "acpa_anti_ccp", label: "Anti-CCP (ACPA)",              unit: "U/mL",   type: "number", refMax: 17 },
      { key: "ana_titolo",    label: "ANA - Titolo",                 unit: "1:n",    type: "text",   placeholder: "es. 1:320" },
      { key: "ana_pattern",   label: "ANA - Pattern",                unit: "",       type: "text",   placeholder: "omogeneo, granulare..." },
      { key: "anti_dsdna",    label: "Anti-dsDNA",                   unit: "UI/mL",  type: "number" },
      { key: "anca_pr3",      label: "ANCA / Anti-PR3 (c-ANCA)",     unit: "UI/mL",  type: "number" },
      { key: "anca_mpo",      label: "ANCA / Anti-MPO (p-ANCA)",     unit: "UI/mL",  type: "number" },
      { key: "anca",          label: "ANCA (generico)",               unit: "",       type: "qual" },
      { key: "antifosfolipidi",label: "Antifosfolipidi (gruppo)",     unit: "",       type: "qual" },
      { key: "anti_sm",       label: "Anti-Sm",                      unit: "",       type: "qual" },
      { key: "anti_rnp",      label: "Anti-RNP/U1RNP",               unit: "",       type: "qual" },
      { key: "anti_ssa_ro",   label: "Anti-SSA/Ro",                  unit: "",       type: "qual" },
      { key: "anti_ssb_la",   label: "Anti-SSB/La",                  unit: "",       type: "qual" },
      { key: "anti_scl70",    label: "Anti-Scl-70",                  unit: "",       type: "qual" },
      { key: "anti_centromero",label: "Anti-centromero (ACA)",       unit: "",       type: "qual" },
      { key: "anti_rnap3",    label: "Anti-RNA polimerasi III",       unit: "",       type: "qual" },
      { key: "anti_pmscl",    label: "Anti-PM/Scl",                  unit: "",       type: "qual" },
      { key: "anti_ku",       label: "Anti-Ku",                      unit: "",       type: "qual" },
      { key: "anti_jo1",      label: "Anti-Jo-1",                    unit: "",       type: "qual" },
      { key: "anti_mi2",      label: "Anti-Mi-2",                    unit: "",       type: "qual" },
      { key: "anti_mda5",     label: "Anti-MDA5",                    unit: "",       type: "qual" },
      { key: "anti_tif1g",    label: "Anti-TIF1γ",                   unit: "",       type: "qual" },
      { key: "anti_nxp2",     label: "Anti-NXP2",                    unit: "",       type: "qual" },
      { key: "anti_srp",      label: "Anti-SRP",                     unit: "",       type: "qual" },
      { key: "anti_hmgcr",    label: "Anti-HMGCR",                   unit: "",       type: "qual" },
      { key: "anti_mcv",      label: "Anti-MCV",                     unit: "U/mL",   type: "number" },
      { key: "lac",           label: "Lupus Anticoagulant (LAC)",    unit: "",       type: "qual" },
      { key: "acl_igg",       label: "Anti-cardiolipina IgG",        unit: "GPL/mL", type: "number" },
      { key: "acl_igm",       label: "Anti-cardiolipina IgM",        unit: "MPL/mL", type: "number" },
      { key: "b2gp1_igg",     label: "Anti-β2GP1 IgG",              unit: "U/mL",   type: "number" },
      { key: "b2gp1_igm",     label: "Anti-β2GP1 IgM",              unit: "U/mL",   type: "number" },
    ],
  },
  sierologie: {
    label: "Sierologie",
    tests: [
      { key: "hbsag",    label: "HBsAg",         unit: "", type: "qual" },
      { key: "hbv",      label: "HBV (gruppo)",  unit: "", type: "qual" },
      { key: "anti_hbs", label: "Anti-HBs",      unit: "", type: "qual" },
      { key: "anti_hbc", label: "Anti-HBc",      unit: "", type: "qual" },
      { key: "anti_hcv", label: "Anti-HCV",      unit: "", type: "qual" },
      { key: "hcv",      label: "HCV (gruppo)",  unit: "", type: "qual" },
      { key: "anti_hiv", label: "Anti-HIV",      unit: "", type: "qual" },
      { key: "hiv",      label: "HIV (gruppo)",  unit: "", type: "qual" },
      { key: "tb_qft",   label: "TB (QFT/IGRA)", unit: "", type: "qual" },
    ],
  },
  urine: {
    label: "Urine / Proteinuria",
    tests: [
      { key: "esame_urine",      label: "Esame urine (EU)",             unit: "",       type: "text",   placeholder: "es. negativo / microematuria" },
      { key: "urine_rbc",        label: "Emazie urine",                 unit: "/campo", type: "number" },
      { key: "urine_wbc",        label: "Leucociti urine",              unit: "/campo", type: "number" },
      { key: "hematuria",        label: "Ematuria (qualitativa)",       unit: "",       type: "qual" },
      { key: "leucocituria",     label: "Leucocituria",                 unit: "",       type: "qual" },
      { key: "hemoglobinuria",   label: "Emoglobinuria",                unit: "",       type: "qual" },
      { key: "proteinuria_stick",label: "Proteinuria stick",            unit: "",       type: "qual" },
      { key: "urinary_casts",    label: "Cilindri urinari",             unit: "",       type: "qual" },
      { key: "urine_sg",         label: "Peso specifico",               unit: "",       type: "number" },
      { key: "urine_ph",         label: "pH urine",                     unit: "",       type: "number" },
      { key: "sedimento_note",   label: "Note sedimento",               unit: "",       type: "text" },
      { key: "proteinuria",      label: "Proteinuria 24h",              unit: "g/24h",  type: "number", refMax: 0.15 },
      { key: "upcr",             label: "Rapporto prot/creatinina (UPCR)", unit: "mg/g", type: "number" },
      { key: "acr",              label: "Rapporto albumina/creatinina (ACR)", unit: "mg/g", type: "number", refMax: 30 },
      { key: "albuminuria",      label: "Albuminuria 24h",              unit: "mg/24h", type: "number" },
    ],
  },
};

export const LAB_PANEL_KEYS = Object.keys(LAB_PANELS);
