// Miscellanea reumatologica: tabelle di riferimento e iter diagnostici

export const MYOSITIS_ANTIBODIES = [
  { antibody: "Anti-Jo1", phenotype: "Antisintetasi", muscle: "✓ miosite classica", skin: "✓", lung: "✓✓ (frequente)", heart: "±", gi: "±", tumor: "✗", other: "Mani da meccanico, artrite" },
  { antibody: "Anti-PL7", phenotype: "Antisintetasi", muscle: "± (spesso lieve)", skin: "±", lung: "✓✓✓ (severa)", heart: "±", gi: "✗", tumor: "✗", other: "ILD dominante" },
  { antibody: "Anti-PL12", phenotype: "Antisintetasi", muscle: "± (spesso assente)", skin: "±", lung: "✓✓✓ (isolata possibile)", heart: "✗", gi: "✗", tumor: "✗", other: "ILD isolata possibile" },
  { antibody: "Anti-EJ", phenotype: "Antisintetasi", muscle: "✓", skin: "±", lung: "✓✓", heart: "✗", gi: "✗", tumor: "✗", other: "Artrite" },
  { antibody: "Anti-OJ", phenotype: "Antisintetasi", muscle: "✓", skin: "±", lung: "✓✓", heart: "✗", gi: "✗", tumor: "✗", other: "Fenotipo classico" },
  { antibody: "Anti-Mi-2", phenotype: "Dermatomiosite classica", muscle: "✓✓", skin: "✓✓✓", lung: "✗ (raro)", heart: "✗", gi: "✗", tumor: "✗", other: "Ottima prognosi" },
  { antibody: "Anti-TIF1-γ", phenotype: "Dermatomiosite paraneoplastica", muscle: "✓", skin: "✓✓✓", lung: "✗", heart: "✗", gi: "✗", tumor: "✓✓✓", other: "Rash severo - screening neoplasia!" },
  { antibody: "Anti-NXP2", phenotype: "Dermatomiosite", muscle: "✓✓ (severa)", skin: "✓", lung: "±", heart: "±", gi: "✓ (disfagia)", tumor: "✓ (adulti)", other: "Calcinosi" },
  { antibody: "Anti-MDA5", phenotype: "DM amiopatica", muscle: "✗ o lieve", skin: "✓✓", lung: "✓✓✓ (RP-ILD)", heart: "✗", gi: "✗", tumor: "✗", other: "Ulcere, rash, prognosi severa" },
  { antibody: "Anti-SAE", phenotype: "Dermatomiosite", muscle: "✓ (tardiva)", skin: "✓✓", lung: "±", heart: "✗", gi: "✓ (disfagia)", tumor: "±", other: "Rash precoce" },
  { antibody: "Anti-SRP", phenotype: "Miopatia necrotizzante", muscle: "✓✓✓", skin: "✗", lung: "✗", heart: "✓ (possibile)", gi: "✗", tumor: "✗", other: "CK molto alte" },
  { antibody: "Anti-HMGCR", phenotype: "Miopatia necrotizzante", muscle: "✓✓✓", skin: "✗", lung: "✗", heart: "✗", gi: "✗", tumor: "±", other: "Associazione con statine" },
  { antibody: "Anti-cN1A", phenotype: "Inclusion body myositis", muscle: "✓ (distale)", skin: "✗", lung: "✗", heart: "✗", gi: "✓ (disfagia)", tumor: "✗", other: "Debolezza asimmetrica" },
];

export const AUTOINFLAMMATORY_DISEASES = [
  { disease: "FMF", onset: "Infanzia", fever: "✓ alta", pattern: "1-3 gg", signs: "Sierositi (peritonite, pleurite)", skin: "Erisipeloide", organs: "Articolazioni, peritoneo", redflag: "Dolore addominale ricorrente", genetics: "MEFV, SAA" },
  { disease: "TRAPS", onset: "Infanzia", fever: "✓ prolungata", pattern: "1-3 settimane", signs: "Mialgie migranti, dolore profondo", skin: "Rash migrante", organs: "Occhio (edema periorbitale)", redflag: "Febbre lunga + dolore migrante", genetics: "TNFRSF1A" },
  { disease: "HIDS / MKD", onset: "Infanzia", fever: "✓ alta", pattern: "3-7 gg", signs: "Adenopatie, diarrea", skin: "Maculo-papulare", organs: "GI", redflag: "Febbre + linfonodi + diarrea", genetics: "MVK, IgD↑" },
  { disease: "FCAS (CAPS)", onset: "Infanzia", fever: "✓ lieve", pattern: "<24h", signs: "Trigger freddo", skin: "Orticarioide", organs: "Articolazioni", redflag: "Freddo → febbre breve", genetics: "NLRP3" },
  { disease: "MWS (CAPS)", onset: "Infanzia", fever: "✓ moderata", pattern: "Giorni", signs: "Ipoacusia progressiva", skin: "Orticarioide", organs: "Rene (amiloidosi)", redflag: "Perdita udito progressiva", genetics: "NLRP3" },
  { disease: "NOMID/CINCA (CAPS)", onset: "Neonatale", fever: "✓ persistente", pattern: "Continuo", signs: "Meningite cronica, artropatia", skin: "Orticarioide persistente", organs: "SNC, osso", redflag: "Rash neonatale + SNC", genetics: "NLRP3, RM/CSF" },
  { disease: "PFAPA", onset: "Infanzia", fever: "✓ alta", pattern: "Regolare (3-6 settimane)", signs: "Aftosi, faringite, adenite", skin: "✗", organs: "ORL", redflag: "Periodicità perfetta", genetics: "Clinico" },
  { disease: "AOSD (Still adulto)", onset: "Adulto", fever: "✓ elevata", pattern: "Quotidiana (quotidian spikes)", signs: "Rash salmonato, artrite", skin: "Evanescente color salmone", organs: "Fegato, milza", redflag: "Ferritina molto alta", genetics: "Ferritina↑↑, gly ferritina ↓" },
  { disease: "Behçet", onset: "Giovane adulto", fever: "±", pattern: "Recidivante", signs: "Aftosi orale/genitale", skin: "Pseudofollicolite", organs: "Occhi, SNC", redflag: "Uveite + aftosi", genetics: "HLA-B51" },
  { disease: "Schnitzler", onset: "Adulto", fever: "✓ cronica", pattern: "Persistente", signs: "Orticaria + gammopatia", skin: "Orticaria", organs: "Osso", redflag: "Orticaria + IgM monoclonale", genetics: "Elettroforesi" },
  { disease: "DIRA", onset: "Neonatale", fever: "✓", pattern: "Continuo", signs: "Pustole severe", skin: "Pustoloso", organs: "Osso", redflag: "Pustolosi neonatale", genetics: "IL1RN" },
  { disease: "PAPA", onset: "Infanzia", fever: "±", pattern: "Recidivante", signs: "Artrite sterile + acne", skin: "Acne severa", organs: "Cute", redflag: "Acne + artrite sterile", genetics: "PSTPIP1" },
  { disease: "VEXAS", onset: "Adulto (>50 aa, M)", fever: "✓ persistente", pattern: "Cronico", signs: "Condriti, vasculiti, citopenie", skin: "Dermatosi neutrofile", organs: "Midollo, cute, polmone", redflag: "Vacuoli mieloidi, MDS associata", genetics: "UBA1 somatica" },
];

export const ANA_PATTERNS = [
  { pattern: "Omogeneo", antibodies: "Anti-dsDNA, istoni", diseases: "LES, LES indotto da farmaci" },
  { pattern: "Speckled (fine/grossolano)", antibodies: "Anti-Sm, RNP, SSA, SSB, Scl-70", diseases: "LES, MCTD, Sjögren, SSc" },
  { pattern: "Nucleolare", antibodies: "Anti-RNAP III, U3-RNP, Th/To, PM-Scl", diseases: "SSc (soprattutto diffusa), overlap" },
  { pattern: "Centromerico", antibodies: "Anti-ACA (CENP-B)", diseases: "SSc limitata, CREST, CBP" },
  { pattern: "Nuclear dots", antibodies: "Anti-Sp100, PML", diseases: "Colangite biliare primitiva (CBP)" },
  { pattern: "Citoplasmatico", antibodies: "Anti-Jo1, Ribosomal P, Mi-2, mitocondriali", diseases: "Miositi, LES (ribosomal P), CBP" },
  { pattern: "NuMA", antibodies: "Anti-NuMA (anti-centrosoma)", diseases: "Sjögren, raro SSc" },
];

export const ICAP_ANA_PATTERNS = [
  {
    code: "AC-1",
    name: "Omogeneo nucleare",
    category: "nuclear",
    antigens: ["Anti-dsDNA", "Anti-istoni", "Anti-nucleosomi"],
    diseases: ["LES", "LES da farmaci", "AIJ", "MCTD"],
    confirmatory: "Anti-dsDNA (ELISA/Farr/IIF su Crithidia luciliae), anti-nucleosomi, anti-istoni",
    notes: "Tra i pattern più frequenti; alta specificità per LES se titolo ≥ 1:160",
    description: "Colorazione uniforme dell'intero nucleo inclusi i cromosomi in metafase. Espressione di anticorpi diretti contro il DNA e le proteine istoniche che compattano la cromatina.",
    workup: "Richiedere anti-dsDNA quantitativi (ELISA + IIF su Crithidia luciliae), anti-nucleosomi, anti-istoni. Se anti-dsDNA positivi: completare profilo LES (C3/C4, anti-Sm, emocromo, sedimento urinario). Considerare anti-istoni in caso di esposizione a farmaci lupogeni (procainamide, idralazina, isoniazide, anti-TNF).",
  },
  {
    code: "AC-2",
    name: "Finemente granulare denso (DFS)",
    category: "nuclear",
    antigens: ["Anti-DFS70", "Anti-LEDGFp75"],
    diseases: ["Soggetti sani", "Aspecifico (varie)"],
    confirmatory: "Anti-DFS70 specifico (ELISA/CIA); esclusione altri ENA",
    notes: "Positività isolata per anti-DFS70 (senza altri ENA) riduce significativamente la probabilità di malattia autoimmune sistemica",
    description: "Granularità fine e densa con colorazione più intensa dei cromosomi metafasici. Morfologia caratteristica che si distingue dal fine speckled (AC-4) per la densità e per l'accentuazione metafasica.",
    workup: "Confermare con test anti-DFS70 specifico. Se anti-DFS70 isolato senza altri autoanticorpi: illustrare al paziente la bassa rilevanza clinica. Se altri ENA co-presenti: procedere con valutazione autoimmune standard.",
  },
  {
    code: "AC-3",
    name: "Centromerico",
    category: "nuclear",
    antigens: ["Anti-CENP-A", "Anti-CENP-B", "Anti-CENP-C"],
    diseases: ["SSc limitata / CREST", "Colangite biliare primitiva (PBC)", "Fenomeno di Raynaud"],
    confirmatory: "Anti-CENP-B (ELISA), anti-CENP-A",
    notes: "~46 puntini discreti per nucleo (uno per centromero); altamente specifico per SSc forma limitata",
    description: "Puntini discreti e uniformi distribuiti nel nucleo corrispondenti ai centromeri dei cromosomi; più evidenti nelle cellule in metafase (46 spots). Pattern tra i più riconoscibili e diagnosticamente rilevanti.",
    workup: "Conferma anti-CENP-B (ELISA). Capillaroscopia (pattern SSc early/active/late). Screening PBC (ALP, GGT, AMA-M2). Ecocardiogramma con stima PAPs (ipertensione polmonare arteriosa frequente in SSc limitata/CREST). PFR con DLCO.",
  },
  {
    code: "AC-4",
    name: "Fine speckled",
    category: "nuclear",
    antigens: ["Anti-SSA/Ro60", "Anti-SSB/La", "Anti-Sm", "Anti-U1-RNP"],
    diseases: ["Sindrome di Sjögren", "LES", "MCTD", "LNE neonatale", "SCLE", "SSc"],
    confirmatory: "Panel ENA: anti-SSA/Ro60, anti-SSB/La, anti-Sm, anti-U1-RNP (LIA/ELISA)",
    notes: "Pattern più frequente in clinica; ampia diagnosi differenziale; conferma antigenospecifica sempre necessaria",
    description: "Granularità fine e uniforme del nucleo, risparmio dei nucleoli, negatività dei cromosomi metafasici. La morfologia da sola non permette di distinguere tra le diverse specificità anticorpali.",
    workup: "Panel ENA completo (SSA/Ro60, SSB/La, Sm, U1-RNP). Valutare clinica per Sjögren (secchezza, biopsia ghiandole salivari, test di Schirmer), LES e MCTD. In donne in età fertile con anti-SSA: counseling su blocco cardiaco congenito neonatale.",
  },
  {
    code: "AC-5",
    name: "Grossolano speckled",
    category: "nuclear",
    antigens: ["Anti-U1-RNP", "Anti-Sm"],
    diseases: ["MCTD (Sharp)", "LES", "Overlap"],
    confirmatory: "Anti-U1-RNP, anti-Sm (LIA/ELISA)",
    notes: "Anti-U1-RNP ad alto titolo è marcatore sierologico caratteristico di MCTD; anti-Sm altamente specifico per LES",
    description: "Granularità grossolana e irregolare del nucleo; cromosomi metafasici negativi; nucleoli solitamente risparmiati. Generalmente espressione di titoli anticorpali più elevati rispetto ad AC-4.",
    workup: "Anti-U1-RNP e anti-Sm (LIA). Se anti-U1-RNP alto e anti-Sm negativo: valutare MCTD (criteri Sharp/Kasukawa). Se anti-Sm positivo: profilo LES completo. Valutare sempre ipertensione polmonare nella MCTD.",
  },
  {
    code: "AC-6",
    name: "Puntini nucleari multipli",
    category: "nuclear",
    antigens: ["Anti-Sp100", "Anti-PML", "Anti-NDP55", "Anti-MJ/NXP2"],
    diseases: ["Colangite biliare primitiva (PBC)", "Overlap epatico"],
    confirmatory: "Anti-Sp100 (ELISA), AMA-M2",
    notes: "≥ 6 puntini discreti per nucleo (domini nucleari PML); fortemente associati a PBC in combinazione con AMA",
    description: "Sei o più puntini fluorescenti discreti distribuiti nel nucleo corrispondenti ai domini PML. Pattern caratteristico e abbastanza specifico, distinto dal centromerico (AC-3) per distribuzione e numero.",
    workup: "AMA-M2 (ELISA), ALP, GGT, bilirubina, IgM, ecografia epatica. Anti-Sp100 per conferma. Se PBC confermata: iniziare UDCA e rivalutare a 12 mesi (criteri di risposta Barcelona/Paris II).",
  },
  {
    code: "AC-7",
    name: "Puntini nucleari rari",
    category: "nuclear",
    antigens: ["Anti-p80-coilina", "Anti-SMN"],
    diseases: ["Aspecifico", "Atrofia muscolare spinale (SMA)"],
    confirmatory: "Anti-coilina (laboratori di riferimento)",
    notes: "Meno di 6 puntini per nucleo (corpi di Cajal/gems); bassa specificità clinica come reperto isolato",
    description: "Meno di sei puntini fluorescenti discreti nel nucleo, corrispondenti ai corpi di Cajal. Morfologicamente distinguibile da AC-6 per il numero ridotto di spots.",
    workup: "Contesto clinico essenziale. Anti-coilina se sospetto clinico di SMA o altra miopatia. Come reperto isolato: rivalutazione clinica e sierologica a 6-12 mesi.",
  },
  {
    code: "AC-8",
    name: "Nucleolare omogeneo",
    category: "nuclear",
    antigens: ["Anti-PM-Scl 75/100", "Anti-RNA polimerasi I"],
    diseases: ["SSc overlap (PM/SSc)", "Polimiosite", "SSc diffusa"],
    confirmatory: "Anti-PM-Scl 75/100 (ELISA), anti-RNAP I",
    notes: "Fluorescenza liscia e omogenea dei nucleoli; PM-Scl associato a overlap miosite/SSc con miopatia infiammatoria",
    description: "Colorazione uniforme e omogenea dei nucleoli; il background nucleare è tipicamente negativo o debolmente positivo. Solo i nucleoli appaiono brillanti.",
    workup: "Anti-PM-Scl 75/100 e anti-RNAP I. Capillaroscopia. Valutazione muscolare (CK, aldolasi, EMG, RM muscolare). HRCT polmonare (ILD). ECG e Holter per coinvolgimento cardiaco.",
  },
  {
    code: "AC-9",
    name: "Nucleolare eterogeneo/grumoso",
    category: "nuclear",
    antigens: ["Anti-U3-RNP (fibrillarina)"],
    diseases: ["SSc diffusa (soprattutto etnia afrocaraibica)", "Overlap"],
    confirmatory: "Anti-U3-RNP/fibrillarina (ELISA, laboratori di riferimento)",
    notes: "Pattern grumoso/irregolare del nucleolo; anti-fibrillarina caratteristico di SSc diffusa ad alto rischio cardiorespiratorio",
    description: "Fluorescenza irregolare e disomogenea dei nucleoli; morfologia variabile con la fase del ciclo cellulare. Distinguibile dall'AC-8 per l'aspetto grumoso e disuniforme.",
    workup: "Anti-fibrillarina (U3-RNP). Valutazione cardiorespiratorio urgente (ILD e ipertensione polmonare comuni). Capillaroscopia, ecografia cardiaca, HRCT, PFR con DLCO.",
  },
  {
    code: "AC-10",
    name: "Nucleolare puntato",
    category: "nuclear",
    antigens: ["Anti-Th/To (Rpp25/Rpp38)", "Anti-NOR90 (hUBF)"],
    diseases: ["SSc limitata", "SSc diffusa (rischio ILD)"],
    confirmatory: "Anti-Th/To (laboratori di riferimento)",
    notes: "1-4 puntini discreti nel nucleolo; anti-Th/To associato a rischio ILD anche nella forma limitata di SSc",
    description: "Puntini fluorescenti discreti all'interno dei nucleoli (1-4 per nucleolo); aspetto puntatiforme distinto dall'omogeneo (AC-8).",
    workup: "Anti-Th/To (laboratorio di riferimento). HRCT torace (rischio ILD significativo). Capillaroscopia. PFR con DLCO (marker precoce ILD). Ecocardiogramma (PAH).",
  },
  {
    code: "AC-11",
    name: "Lamina nucleare",
    category: "nuclear",
    antigens: ["Anti-lamin A", "Anti-lamin B", "Anti-lamin C"],
    diseases: ["LES", "LES da farmaci", "Laminopatie (Emery-Dreifuss)"],
    confirmatory: "Anti-lamin B (ELISA)",
    notes: "Bordo liscio e uniforme intorno al nucleo (envelope nucleare liscio); relativamente aspecifico; frequente in LES farmaco-indotto",
    description: "Fluorescenza liscia e uniforme del bordo nucleare, corrispondente alla lamina nucleare. Distinto dall'AC-12 che mostra un bordo puntato.",
    workup: "Revisione farmaci (procainamide, idralazina, isoniazide, anti-TNF). Anti-lamin B (ELISA). Se non farmaco-correlato: completare profilo LES e valutazione autoimmune sistemica.",
  },
  {
    code: "AC-12",
    name: "Envelope nucleare puntato",
    category: "nuclear",
    antigens: ["Anti-gp210", "Anti-p62", "Anti-nucleoporina"],
    diseases: ["Colangite biliare primitiva (PBC)"],
    confirmatory: "Anti-gp210, anti-p62 (ELISA)",
    notes: "Puntini/granuli sull'envelope nucleare (pori nucleari); anti-gp210 altamente specifico per PBC",
    description: "Fluorescenza puntata o granulare sull'envelope nucleare corrispondente al complesso del poro nucleare; morfologicamente distinto dalla lamina liscia (AC-11).",
    workup: "AMA-M2, ALP, GGT, IgM. Anti-gp210 e anti-p62 per conferma PBC. La co-positività AMA + anti-gp210 ha altissima specificità diagnostica per PBC.",
  },
  {
    code: "AC-13",
    name: "PCNA-like",
    category: "nuclear",
    antigens: ["Anti-PCNA (antigene nucleare di proliferazione)"],
    diseases: ["LES (raro, ma specifico)"],
    confirmatory: "Anti-PCNA (ELISA, immunoprecipitazione)",
    notes: "Raro ma altamente specifico per LES; pattern variabile in base alla fase del ciclo cellulare; possibile associazione con nefrite lupica",
    description: "Pattern nucleare variabile (da puntinato a diffuso) correlato con la fase proliferativa: le cellule in fase S mostrano colorazione più intensa e distinta.",
    workup: "Profilo LES completo (anti-dsDNA, anti-Sm, C3/C4, urine, emocromo). Anti-PCNA ha alta specificità per LES pur essendo raro; ricercare segni di nefrite lupica (proteinuria, sedimento).",
  },
  {
    code: "AC-14",
    name: "CENP-F-like",
    category: "nuclear",
    antigens: ["Anti-CENP-F"],
    diseases: ["Paraneoplastico", "Aspecifico (varie)"],
    confirmatory: "Anti-CENP-F (immunoprecipitazione, laboratori di riferimento)",
    notes: "Puntini nucleari in interfase, colorazione brillante dei cinetocori in metafase; possibile associazione con neoplasie occulte",
    description: "Puntini nucleari variabili in interfase con intensa colorazione dei cinetocori nelle cellule in metafase. Morfologicamente simile ad AC-3 ma distinto per numero e distribuzione degli spots.",
    workup: "Screening neoplastico adeguato all'età (TC tronco, markers tumorali, mammografia, colonscopia). Rivalutazione ANA a 6-12 mesi se il pattern persiste senza causa identificata.",
  },
  {
    code: "AC-15",
    name: "Fibrillare citoplasmatico lineare",
    category: "cytoplasmic",
    antigens: ["Anti-actina (SMA)", "Anti-smooth muscle actin"],
    diseases: ["Epatite autoimmune tipo 1 (AIH-1)", "Overlap epatico"],
    confirmatory: "Anti-SMA su substrato tessutale (stomaco/rene/fegato); anti-actina F (ELISA)",
    notes: "Colorazione lineare fibrillare citoplasmatica lungo i filamenti di actina; SMA ≥ 1:80 con anti-actina è marcatore diagnostico chiave di AIH-1",
    description: "Fluorescenza lineare fibrillare nel citoplasma lungo i filamenti di actina (fibre di stress). Distinto dal pattern fibrillare filamentoso (AC-16).",
    workup: "Transaminasi, bilirubina, IgG totali (elevati in AIH). Anti-SMA su tessuto. Biopsia epatica. Anti-LKM1 per escludere AIH tipo 2. Anti-LC1 per variante AIH tipo 2.",
  },
  {
    code: "AC-16",
    name: "Fibrillare citoplasmatico filamentoso",
    category: "cytoplasmic",
    antigens: ["Anti-vimentina", "Anti-cheratina"],
    diseases: ["Aspecifico", "Malattia infiammatoria intestinale (IBD)"],
    confirmatory: "Anti-vimentina (ELISA)",
    notes: "Colorazione filiforme nel citoplasma; generalmente bassa specificità come reperto isolato; possibile in IBD",
    description: "Fluorescenza filiforme/reticolare nel citoplasma seguendo filamenti intermedi (vimentina, cheratina). Distinto dalla colorazione lineare di actina (AC-15).",
    workup: "Contesto clinico necessario. Se sintomi intestinali: calprotectina fecale, colonscopia, p-ANCA perinucleare. Come reperto isolato: bassa specificità.",
  },
  {
    code: "AC-17",
    name: "Fibrillare citoplasmatico segmentale",
    category: "cytoplasmic",
    antigens: ["Anti-alfa-actinina"],
    diseases: ["LES", "Malattia infiammatoria intestinale", "Epatite autoimmune"],
    confirmatory: "Anti-alfa-actinina (ELISA)",
    notes: "Colorazione segmentale/interrotta nel citoplasma; anti-alfa-actinina può essere presente in LES attivo e IBD",
    description: "Pattern fibrillare con interruzioni/segmenti nel citoplasma, seguendo la distribuzione dell'alfa-actinina nelle cellule non muscolari.",
    workup: "Anti-alfa-actinina (ELISA). Se LES sospetto: profilo LES completo. Se IBD: valutazione endoscopica. Transaminasi e IgG se sospetto AIH.",
  },
  {
    code: "AC-18",
    name: "Citoplasmatico finemente granulare denso",
    category: "cytoplasmic",
    antigens: ["Anti-Jo-1 (HisRS)", "Anti-PL-7 (ThrRS)", "Anti-PL-12 (AlaRS)", "Anti-EJ (GlyRS)", "Anti-OJ (IleRS)", "Anti-KS (AsnRS)"],
    diseases: ["Sindrome anti-sintetasi (ILD + miosite + artrite + Raynaud + mani da meccanico + febbre)"],
    confirmatory: "Anti-Jo-1 (ELISA); panel miosite esteso (PL-7, PL-12, EJ, OJ, KS, Ha, Zo)",
    notes: "Anti-Jo-1 è il più frequente; ILD può precedere o dominare rispetto alla miosite; HRCT urgente",
    description: "Fluorescenza citoplasmatica finemente granulare e densa, spesso con piccoli nuclei debolmente reattivi. Le cellule con citoplasma abbondante mostrano il pattern più chiaramente.",
    workup: "Panel miosite-specifici e associati (Jo-1, PL-7, PL-12, EJ, OJ; Ro52, PM-Scl). CK, aldolasi. HRCT torace (ILD spesso grave). EMG, RM muscolare. Biopsia muscolare se diagnosi incerta. Screening oncologico se TIF1-γ o NXP2.",
  },
  {
    code: "AC-19",
    name: "Citoplasmatico puntato discreto",
    category: "cytoplasmic",
    antigens: ["Anti-GW182/TNGW1", "Anti-Su/Ago2 (P-bodies)"],
    diseases: ["Colangite biliare primitiva", "Sindrome di Sjögren", "LES", "AR"],
    confirmatory: "Anti-GW182 (laboratori di riferimento)",
    notes: "Pochi puntini discreti citoplasmatici (GW bodies/P-bodies); significato clinico principalmente di ricerca; test commerciali limitati",
    description: "Da 5 a 20 puntini fluorescenti discreti nel citoplasma corrispondenti ai P-bodies (granuli di processazione dell'mRNA).",
    workup: "Contesto clinico necessario. Escludere PBC, Sjögren, LES clinicamente. Laboratorio di riferimento per conferma se necessario.",
  },
  {
    code: "AC-20",
    name: "Citoplasmatico fine speckled",
    category: "cytoplasmic",
    antigens: ["Anti-SSA/Ro52 (TRIM21)", "Anti-SSB/La"],
    diseases: ["Sindrome di Sjögren", "LES", "Lupus neonatale (LNE)", "SCLE", "Overlap miosite"],
    confirmatory: "Anti-Ro52 (TRIM21) specifico, anti-La (ELISA/LIA)",
    notes: "Anti-Ro52 è marcatore indipendente di rischio ILD nelle miopatie infiammatorie overlap; counseling gravidanza essenziale",
    description: "Granularità fine nel citoplasma, talvolta con componente nucleare coesistente. Anti-Ro52 (TRIM21) è un antigene citoplasmatico distinto da Ro60.",
    workup: "Anti-Ro52 (TRIM21) specifico, anti-La. Counseling su rischio blocco cardiaco congenito neonatale (anti-Ro52/Ro60). Valutazione Sjögren. Se miosite: panel sintetasi/miosite. HRCT se ILD sospetta.",
  },
  {
    code: "AC-21",
    name: "Citoplasmatico reticolare/AMA",
    category: "cytoplasmic",
    antigens: ["Anti-PDC-E2 (M2)", "Anti-OGDC-E2", "Anti-BCOADC-E2"],
    diseases: ["Colangite biliare primitiva (PBC)"],
    confirmatory: "AMA-M2 (ELISA), anti-PDC-E2; ALP, GGT",
    notes: "Pattern reticolare citoplasmatico seguendo la distribuzione mitocondriale; altamente specifico per PBC (> 95%); brillante nelle cellule di tubulo renale distale",
    description: "Fluorescenza reticolare/filamentosa nel citoplasma seguendo la distribuzione dei mitocondri. Particolarmente brillante nelle cellule di tubulo distale renale su substrato tessutale. Uno dei pattern più diagnosticamente rilevanti.",
    workup: "ALP, GGT, IgM, AMA-M2 (ELISA), ecografia epatica. Se AMA positivo e ALP elevata: diagnosi di PBC anche senza biopsia. Iniziare UDCA. Rivalutare risposta biochimica a 12 mesi.",
  },
  {
    code: "AC-22",
    name: "Polare/Golgi-like",
    category: "cytoplasmic",
    antigens: ["Anti-giantina", "Anti-GM130", "Anti-golgin-97", "Anti-golgin-95"],
    diseases: ["Varie malattie autoimmuni", "LES", "Sindrome di Sjögren", "Infezioni (HIV, EBV)"],
    confirmatory: "Anti-giantina (laboratori di riferimento)",
    notes: "Aggregati polari citoplasmatici corrispondenti all'apparato di Golgi; relativamente raro; escludere infezioni virali",
    description: "Fluorescenza in aggregati polari/juxtanucleari nel citoplasma corrispondente all'apparato di Golgi. Morfologia caratteristica a granuli juxtanucleari compatti.",
    workup: "Escludere infezioni (HIV, EBV, HCV). Panel autoimmune se sospetto clinico. Anti-giantina se disponibile (laboratorio di riferimento).",
  },
  {
    code: "AC-23",
    name: "Bastoncini e anelli (Rods and Rings)",
    category: "cytoplasmic",
    antigens: ["Anti-IMPDH2 (inosina monofosfato deidrogenasi 2)"],
    diseases: ["Associato a trattamento HCV (IFN-pegilato + ribavirina)", "Raro de novo in malattie autoimmuni"],
    confirmatory: "Anti-IMPDH2 (laboratori di riferimento)",
    notes: "Strutture citoplasmatiche a forma di bastoncino e anello; fortemente associato al trattamento anti-HCV; generalmente reperto benigno nel contesto",
    description: "Strutture citoplasmatiche allungate (bastoncini) e circolari (anelli) altamente caratteristiche. Morfologia unica, facilmente riconoscibile e difficilmente confondibile con altri pattern.",
    workup: "Revisione anamnesi farmacologica (IFN-pegilato + ribavirina per HCV). Se de novo senza trattamento HCV: valutazione autoimmune. Reperto generalmente benigno nel contesto HCV.",
  },
  {
    code: "AC-24",
    name: "Fibre del fuso mitotico",
    category: "mitotic",
    antigens: ["Anti-NuMA-1 (apparato mitotico nucleare)"],
    diseases: ["Sindrome di Sjögren", "Varie (spesso aspecifico)"],
    confirmatory: "Anti-NuMA-1 (laboratori di riferimento)",
    notes: "Colorazione delle fibre del fuso nelle cellule in mitosi; relativamente raro; associazione con Sjögren descritta in letteratura",
    description: "Fluorescenza delle fibre del fuso mitotico visibile solo nelle cellule in divisione; il nucleo in interfase è tipicamente negativo o debolmente positivo.",
    workup: "Valutazione Sjögren (secchezza oculare e orale, test di Schirmer, biopsia ghiandole salivari, anti-SSA/La). Se Sjögren negativo: rivalutazione sierologica a 12 mesi.",
  },
  {
    code: "AC-25",
    name: "NuMA-like (metafasico)",
    category: "mitotic",
    antigens: ["Anti-NuMA-2"],
    diseases: ["Aspecifico"],
    confirmatory: "Anti-NuMA-2 (laboratori di riferimento)",
    notes: "Pattern distinto da AC-24; colorazione delle regioni polari in metafase; limitate associazioni cliniche note",
    description: "Colorazione dei poli del fuso mitotico (regioni polari) nelle cellule in metafase; distinto dalle fibre del fuso (AC-24).",
    workup: "Contesto clinico richiesto. Bassa specificità come reperto isolato. Rivalutazione raccomandata a 6-12 mesi.",
  },
  {
    code: "AC-26",
    name: "Centriolo/Centrosoma",
    category: "mitotic",
    antigens: ["Anti-centrosoma", "Anti-pericentrina", "Anti-cenexina (ODF2)"],
    diseases: ["SSc", "Fenomeno di Raynaud primitivo", "Infezioni croniche (HCV)"],
    confirmatory: "Anti-centrosoma panel (laboratori di riferimento)",
    notes: "1-2 puntini discreti per cellula vicino al nucleo (visibili anche in interfase); associazione con SSc e Raynaud; escludere infezioni virali",
    description: "1-2 puntini discreti e brillanti per cellula adiacenti al nucleo (centrioli/centrosoma). Visibili sia in interfase che in mitosi, caratteristica che distingue questo pattern dagli altri mitotico-specifici.",
    workup: "Capillaroscopia. SSc workup (anti-Scl-70, anti-CENP-B, HRCT, ecografia cardiaca). Sierologie virali (HCV). Anti-centrosoma panel se disponibile.",
  },
  {
    code: "AC-27",
    name: "Mid-body",
    category: "mitotic",
    antigens: ["Anti-midbody (bersagli multipli)"],
    diseases: ["Aspecifico"],
    confirmatory: "Saggi di ricerca (laboratori di riferimento)",
    notes: "Colorazione del midbody nella citochinesi; reperto raro con bassa specificità clinica nota",
    description: "Fluorescenza della struttura midbody nelle cellule in fase di citochinesi (divisione avanzata); raramente visualizzabile nelle preparazioni standard.",
    workup: "Contesto clinico essenziale. Rivalutazione clinica e sierologica raccomandata. Bassa specificità come reperto isolato.",
  },
  {
    code: "AC-28",
    name: "Cromosomico metafasico",
    category: "mitotic",
    antigens: ["Anti-CENP-E", "Anti-CENP-F correlati", "Antigeni cromosomici vari"],
    diseases: ["Paraneoplastico", "Aspecifico"],
    confirmatory: "Immunoprecipitazione (laboratori di riferimento)",
    notes: "Colorazione dei cromosomi metafasici (esclusi i centromeri); possibile associazione paraneoplastica se comparsa de novo",
    description: "Fluorescenza delle strutture cromosomiche in metafase, distinta dal pattern centromerico (AC-3) per la colorazione diffusa dei cromosomi anziché dei soli centromeri.",
    workup: "Screening neoplastico se de novo (TC tronco, markers tumorali). Rivalutazione ANA a 6-12 mesi. Immunoprecipitazione per caratterizzazione anticorpale.",
  },
  {
    code: "AC-29",
    name: "Topo I-like (fine speckled nucleare/citoplasmatico)",
    category: "nuclear",
    antigens: ["Anti-topoisomerasi I (anti-Scl-70)"],
    diseases: ["SSc diffusa", "ILD grave da SSc"],
    confirmatory: "Anti-Scl-70/topoisomerasi I (ELISA, LIA)",
    notes: "Fine speckled nucleare con componente citoplasmatica; altamente specifico per SSc diffusa; principale marcatore di rischio ILD in SSc",
    description: "Fluorescenza finemente granulare nucleare con possibile estensione citoplasmatica e parziale coinvolgimento nucleolare; morfologia spesso sovrapponibile a AC-4 ma con diversa specificità anticorpale.",
    workup: "Conferma anti-Scl-70 (ELISA/LIA). HRCT torace urgente (ILD molto frequente e grave). PFR con DLCO. Capillaroscopia. Ecocardiogramma (PAH). Valutazione renale (rischio crisi renale sclerodermica). Follow-up semestrale.",
  },
];

export const DIAGNOSTIC_ALGORITHMS = [
  {
    id: "iperckemia",
    name: "iperCKemia - iter diagnostico",
    category: "Algoritmi",
    intro: "Approccio sistematico all'iperCKemia, distinzione benigna vs patologica e identificazione di cause reumatologiche.",
    steps: [
      {
        title: "1. Conferma e ripetizione",
        items: [
          "Confermare con 2-3 dosaggi ripetuti a distanza (variabilità fisiologica).",
          "Riposo 5-7 giorni prima del dosaggio (evitare attività fisica intensa, traumi, EMG, iniezioni i.m.).",
          "Escludere cause benigne: esercizio fisico, fans, alcol, etnia (afrocaraibici), macro-CK.",
        ],
      },
      {
        title: "2. Valutazione clinica",
        items: [
          "Anamnesi: farmaci (statine, fibrati, steroidi, colchicina), familiarità (miopatie ereditarie), esordio, debolezza, mialgie, crampi, dolore post-sforzo.",
          "Esame obiettivo: debolezza prossimale vs distale, simmetrica/asimmetrica, segni cutanei (rash eliotropo, Gottron), segni sistemici.",
          "Red flags: disfagia, disfonia, insufficienza respiratoria, miocardite, rash.",
        ],
      },
      {
        title: "3. Esami di secondo livello",
        items: [
          "Emocromo, VES, PCR, funzione epato-renale, TSH (ipotiroidismo), elettroliti, vit D.",
          "Troponina I (distinguere danno muscolare vs cardiaco; troponina T può essere elevata in miopatie).",
          "Aldolasi, LDH, AST/ALT (profilo muscolare).",
          "Esame urine: mioglobinuria se CK >5000 U/L.",
          "Ferritina (iperferritinemia in AOSD, HLH, miositi severe).",
        ],
      },
      {
        title: "4. Screening autoimmune (se sospetto miosite)",
        items: [
          "ANA + panel miosite-specifici (Jo-1, PL-7, PL-12, EJ, OJ, Mi-2, TIF1-γ, NXP2, MDA5, SAE, SRP, HMGCR, cN1A).",
          "Anticorpi miosite-associati: Ro/SSA (52/60 kDa), PM-Scl, Ku, U1-RNP.",
          "Capillaroscopia (pattern SSc in overlap).",
        ],
      },
      {
        title: "5. Esami strumentali",
        items: [
          "EMG-ENG: pattern miopatico (MUAP brevi, polifasici, attività spontanea).",
          "RM muscolare (cosce): edema (STIR), atrofia, sostituzione adiposa; utile per guidare biopsia.",
          "Biopsia muscolare se diagnosi incerta: infiltrato infiammatorio, necrosi, atrofia perifascicolare (DM), vacuoli orlati (IBM).",
        ],
      },
      {
        title: "6. Diagnosi differenziale",
        items: [
          "Miopatie infiammatorie: DM, PM, IMNM, ASS, IBM, overlap.",
          "Miopatie da farmaci: statine (anti-HMGCR), colchicina, GC (senza CK↑), fibrati.",
          "Endocrine: ipotiroidismo, Cushing, iperparatiroidismo.",
          "Metaboliche: glicogenosi (McArdle), disturbi mitocondriali, deficit CPT2.",
          "Genetiche: distrofie muscolari, canalopatie.",
          "Rabdomiolisi acuta: trauma, infezioni, drugs of abuse.",
        ],
      },
      {
        title: "Red flags - ricovero urgente",
        items: [
          "CK >10.000 U/L con rabdomiolisi, AKI, iperkaliemia.",
          "Insufficienza respiratoria (coinvolgimento muscoli respiratori/diaframma).",
          "Disfagia severa con rischio ab ingestis.",
          "Miocardite (troponina I elevata, sintomi cardiaci).",
        ],
      },
    ],
  },
  {
    id: "aftosi_orale_ricorrente",
    name: "Aftosi orale ricorrente - iter diagnostico",
    category: "Algoritmi",
    intro: "Valutazione sistematica dell'aftosi orale ricorrente (>3 episodi/anno), distinzione benigna vs sistemica.",
    steps: [
      {
        title: "1. Caratterizzazione clinica",
        items: [
          "Numero, dimensioni e morfologia: minor (<1 cm, guarigione <14 gg, senza cicatrice), major (>1 cm, profonde, cicatrizzanti), herpetiformi (multiple piccole).",
          "Sede: solo orale vs oro-genitale (Behçet).",
          "Frequenza, durata, fattori scatenanti (stress, ciclo mestruale, alimenti).",
          "Sintomi sistemici associati: febbre, artralgie, uveite, lesioni cutanee, GI.",
        ],
      },
      {
        title: "2. Escludere cause locali",
        items: [
          "Trauma meccanico cronico (dentizione, protesi).",
          "Deficit carenziali: vit B12, folati, ferro, zinco.",
          "Intolleranze alimentari (glutine, lattosio, nickel).",
          "Infezioni: HSV (coltura, PCR), HIV, sifilide, candidosi.",
        ],
      },
      {
        title: "3. Screening nutrizionale",
        items: [
          "Emocromo con MCV, ferritina, sideremia, transferrina.",
          "Vit B12, folati, vit D, zinco.",
          "Anti-transglutaminasi IgA + IgA totali (celiachia).",
        ],
      },
      {
        title: "4. Screening autoimmune e sistemico",
        items: [
          "ANA, ENA panel, ANCA, HLA-B51 (Behçet), HLA-B27 (spondiloartriti).",
          "Immunoglobuline (deficit IgA può associarsi ad aftosi).",
          "Patergy test (Behçet): puntura con ago sterile → lesione pustolare >48h = positivo.",
          "Valutazione oftalmologica (uveite subclinica).",
        ],
      },
      {
        title: "5. Valutazione GI",
        items: [
          "MICI (Crohn, RCU): calprotectina fecale, colonscopia se sospetto.",
          "Celiachia: sierologia + eventuale biopsia duodenale.",
          "Sindrome di Behçet con coinvolgimento intestinale.",
        ],
      },
      {
        title: "6. Diagnosi differenziale principale",
        items: [
          "RAS (recurrent aphthous stomatitis) - diagnosi di esclusione.",
          "Malattia di Behçet (aftosi orale + ≥2 di: aftosi genitale, uveite, lesioni cutanee, patergy+).",
          "PFAPA (nei bambini): periodico + faringite + adenite.",
          "MICI: Crohn soprattutto.",
          "Lupus (aftosi palatale non dolente spesso).",
          "Sindrome di MAGIC (mouth and genital ulcers with inflamed cartilage - overlap Behçet + policondrite).",
          "Deficit di IgA o altre immunodeficienze.",
          "Ciclica/neutropenica: neutropenia ciclica.",
        ],
      },
      {
        title: "Criteri ICBD 2014 Behçet (accessibili dalla pagina Criteri)",
        items: [
          "Aftosi orale (OBBLIGATORIA, 2 punti), aftosi genitale (2), lesioni oculari (2), lesioni cutanee (1), manifestazioni neurologiche (1), manifestazioni vascolari (1), patergy test + (1). Soglia ≥4.",
        ],
      },
    ],
  },
  {
    id: "eritema_nodoso",
    name: "Eritema nodoso - iter diagnostico",
    category: "Algoritmi",
    intro: "Pannicolite settale classica. L'eritema nodoso è una REAZIONE cutanea, quasi sempre secondaria: la priorità è identificare la causa.",
    steps: [
      {
        title: "1. Conferma diagnostica",
        items: [
          "Clinica: noduli eritematosi dolenti, caldi, regioni pretibiali (tipicamente bilaterali simmetrici), 1-5 cm, non ulcerativi.",
          "Evoluzione: fase evolutiva simile ad ematoma (rosso → giallo-verde → bruno), risoluzione senza cicatrice in 4-8 settimane.",
          "Accompagnato da febbricola, artralgie, malessere generale.",
          "Biopsia solo se atipico: mostra pannicolite SETTALE senza vasculite.",
        ],
      },
      {
        title: "2. Cause principali da escludere",
        items: [
          "Infezioni: streptococco β-emolitico A (faringite recente, ASLO), TBC (IGRA, Rx torace), Yersinia (coprocoltura), Mycoplasma, Chlamydia, virus (EBV, HCV, HIV).",
          "Sarcoidosi: linfoadenopatie ilari bilaterali + EN + artralgie = Sindrome di Löfgren.",
          "MICI: sospettare se sintomi GI, calprotectina fecale, colonscopia.",
          "Farmaci: estroprogestinici, antibiotici (sulfamidici, penicilline), FANS, JAK-i.",
          "Gravidanza.",
          "Vasculiti / altre malattie autoimmuni: Behçet, AR, LES.",
          "Neoplasie (raro): linfomi, leucemie.",
          "Idiopatica (~30-50% dei casi).",
        ],
      },
      {
        title: "3. Esami di primo livello",
        items: [
          "Emocromo, VES, PCR (elevate).",
          "Tampone faringeo + ASLO (streptococco).",
          "Rx torace (adenopatie ilari - sarcoidosi, TBC primaria).",
          "IGRA (Quantiferon) o test di Mantoux per TBC.",
          "Funzione epato-renale, elettroliti.",
          "β-hCG in donne in età fertile.",
        ],
      },
      {
        title: "4. Esami di secondo livello (in base al sospetto)",
        items: [
          "ACE sierico, lisozima, calcemia, calciuria 24h (sarcoidosi).",
          "HRCT torace ad alta risoluzione se Rx dubbia.",
          "Coprocoltura + ricerca Yersinia (se sintomi GI).",
          "Sierologie: EBV, CMV, HCV, HIV, sifilide, Mycoplasma.",
          "ANA, ENA, ANCA se sospetto autoimmune.",
          "Calprotectina fecale, colonscopia se sospetto MICI.",
          "HLA-B51, patergy test se sospetto Behçet.",
        ],
      },
      {
        title: "5. Sindrome di Löfgren",
        items: [
          "Triade: eritema nodoso + adenopatie ilari bilaterali + poliartrite migrante delle caviglie.",
          "Patognomonica di sarcoidosi acuta.",
          "Ottima prognosi: risoluzione spontanea in 6-24 mesi in >80% dei casi.",
          "Non sempre necessita biopsia se presentazione tipica.",
        ],
      },
      {
        title: "6. Trattamento",
        items: [
          "Riposo, elevazione arti inferiori, calze elastiche a compressione graduata.",
          "FANS (naprossene, indometacina) come prima scelta per dolore.",
          "Ioduro di potassio (300-900 mg/die): opzione storica, efficace.",
          "Colchicina 1 mg/die: efficace, specialmente in Behçet o recidivante.",
          "GC sistemici (prednisone 20-40 mg/die) in forme severe, refrattarie o associate a patologia sistemica che lo richieda.",
          "Trattamento eziologico della causa sottostante (antibiotici, immunosoppressori per MICI/sarcoidosi, ecc.).",
        ],
      },
    ],
  },
  {
    id: "raynaud",
    name: "Fenomeno di Raynaud - distinzione primario vs secondario",
    category: "Algoritmi",
    intro: "Algoritmo di valutazione per distinguere il Raynaud primario (benigno) dal secondario (spia di malattia autoimmune).",
    steps: [
      {
        title: "Caratteristiche del Raynaud PRIMARIO (Allen & Brown)",
        items: [
          "Esordio generalmente giovane (15-30 aa), sesso femminile.",
          "Simmetrico, bilaterale, senza necrosi/ulcere.",
          "Assenza di segni/sintomi di malattia sistemica.",
          "Capillaroscopia NORMALE.",
          "ANA negativi / titolo basso (<1:160 aspecifico).",
          "VES e PCR normali.",
          "Assenza di alterazioni vascolari periferiche.",
        ],
      },
      {
        title: "Red flags per Raynaud SECONDARIO",
        items: [
          "Esordio >30-40 anni (soprattutto uomini).",
          "Asimmetrico, monolaterale o solo agli arti superiori.",
          "Ulcere digitali, pitting scars, gangrena.",
          "Sintomi sistemici: artralgie, xerostomia, dispnea, disfagia, mialgie.",
          "Puffy fingers, sclerodattilia, telangiectasie.",
          "Capillaroscopia con pattern sclerodermico (early/active/late).",
          "ANA positivi (soprattutto ACA, Scl-70, RNAP III).",
          "VES o PCR elevate.",
        ],
      },
      {
        title: "Esami consigliati",
        items: [
          "Capillaroscopia periungueale (OBBLIGATORIA): distingue pattern normale/aspecifico vs SSc.",
          "ANA (IIF su HEp-2), ENA panel, ACA, Scl-70, RNAP III.",
          "Emocromo, VES, PCR, funzione tiroidea (ipotiroidismo può dare Raynaud secondario).",
          "Criogolbuline, FR, elettroforesi.",
          "Sospetto vasculopatia: ecografia arterie arti superiori, angio-RM se trombosi.",
        ],
      },
      {
        title: "Cause principali di Raynaud secondario",
        items: [
          "SSc (più frequente), VEDOSS.",
          "MCTD, LES, Sjögren.",
          "Miositi (soprattutto ASS).",
          "Vasculiti: Buerger (tromboangioite obliterante).",
          "Farmaci: β-bloccanti, derivati ergotaminici, bleomicina, chemioterapici.",
          "Ostruzioni vascolari: trombosi, sindrome dello stretto toracico.",
          "Endocrine: ipotiroidismo.",
          "Ematologiche: crioglobulinemie, policitemia, mieloma.",
        ],
      },
      {
        title: "Trattamento",
        items: [
          "Misure non farmacologiche: evitare freddo, fumo, β-bloccanti, stress; guanti termici.",
          "Prima linea: calcio-antagonisti diidropiridinici (nifedipina 30-60 mg/die, amlodipina).",
          "Seconda linea: PDE-5 inibitori (sildenafil, tadalafil).",
          "Ulcere digitali attive: iloprost e.v. in cicli; bosentan per prevenzione nuove ulcere (SSc).",
          "Casi refrattari: simpaticectomia digitale, botulino locale.",
        ],
      },
    ],
  },
  {
    id: "iperferritinemia",
    name: "Iperferritinemia in reumatologia",
    category: "Algoritmi",
    intro: "Iperferritinemia severa (>1000 µg/L) è un red flag reumatologico: orienta verso malattie iperinfiammatorie (AOSD, MAS, HLH).",
    steps: [
      {
        title: "Soglie di allarme",
        items: [
          "Ferritina >500 µg/L: sospettare condizione infiammatoria.",
          "Ferritina >1000 µg/L: red flag reumatologico, AOSD probabile.",
          "Ferritina >10.000 µg/L: considerare MAS/HLH (emergenza).",
          "Frazione glicata della ferritina <20%: altamente specifica per AOSD.",
        ],
      },
      {
        title: "Cause principali",
        items: [
          "AOSD (Still dell'adulto): febbre spikes, rash salmone, artrite, leucocitosi neutrofila, transaminasi↑, faringodinia.",
          "Sindrome da attivazione macrofagica (MAS): complicanza di AOSD/sJIA, LES, Kawasaki; pancitopenia, CID, ferritina >10.000.",
          "Emofagocitosi linfoistiocitaria (HLH): forma primitiva (genetica) o secondaria (infezioni, tumori, autoimmuni).",
          "Infezioni severe (sepsi, virali come EBV, CMV, HIV, COVID-19).",
          "Neoplasie (linfomi, leucemie).",
          "Sovraccarico ferro: emocromatosi (ma ferritina in genere <1500-2000, con transferrina saturata ↑↑).",
          "Epatopatie (steatoepatite).",
        ],
      },
      {
        title: "Criteri HLH-2004 (5 su 8 richiesti)",
        items: [
          "Febbre >7 gg.",
          "Splenomegalia.",
          "Citopenia ≥2 linee (Hb <9, piastrine <100, neutrofili <1).",
          "Ipertrigliceridemia >265 mg/dL e/o ipofibrinogenemia <150 mg/dL.",
          "Emofagocitosi in midollo/milza/linfonodi.",
          "Attività NK ridotta/assente.",
          "Ferritina >500 µg/L (tipicamente >10.000 in HLH).",
          "CD25 solubile (sIL-2R) elevato >2400 U/mL.",
        ],
      },
      {
        title: "Criteri H-score (MAS)",
        items: [
          "Score calcolato con: temperatura, organomegalia, citopenie, trigliceridi, fibrinogeno, transaminasi, ferritina, emofagocitosi, immunosoppressione preesistente.",
          "Score >169: alta probabilità di MAS/HLH (93% sens, 86% spec).",
          "Online: saintantoine.aphp.fr/score/",
        ],
      },
      {
        title: "Approccio terapeutico urgente",
        items: [
          "MAS/HLH: boli di metilprednisolone 500-1000 mg x 3 gg + IVIg + eventuale anakinra/etoposide.",
          "AOSD senza MAS: GC (prednisone 0.5-1 mg/kg), poi steroid-sparing (MTX, anakinra, canakinumab, tocilizumab).",
          "Cercare e trattare trigger infettivo/neoplastico sottostante.",
        ],
      },
    ],
  },
  {
    id: "uveite",
    name: "Uveite - approccio reumatologico",
    category: "Algoritmi",
    intro: "L'uveite (infiammazione del tratto uveale) è frequente in reumatologia. La classificazione anatomica (anteriore, intermedia, posteriore, panuveite) orienta l'etiologia.",
    steps: [
      {
        title: "Classificazione anatomica (SUN)",
        items: [
          "Anteriore (irite, iridociclite): 80% dei casi. Cellule in camera anteriore.",
          "Intermedia (pars planitis): vitreite, snowballs.",
          "Posteriore (coroidite/retinite): alterazioni fundus.",
          "Panuveite: tutti i segmenti.",
        ],
      },
      {
        title: "Uveite anteriore acuta - cause reumatologiche",
        items: [
          "Spondiloartriti (HLA-B27+): uveite anteriore acuta ricorrente, unilaterale alternante (40% dei pazienti SpA).",
          "Artrite idiopatica giovanile (JIA): uveite cronica anteriore, spesso bilaterale, PAUCI-sintomatica (screening oftalmologico obbligatorio).",
          "Sarcoidosi: granulomatosa, può essere anteriore, intermedia o posteriore.",
          "Behçet: panuveite con ipopion, vasculite retinica, severa.",
          "Sindrome di Cogan: uveite + sintomi vestibolo-cocleari.",
        ],
      },
      {
        title: "Screening reumatologico",
        items: [
          "HLA-B27 (uveite anteriore ricorrente).",
          "ACE sierico, lisozima, calcemia, Rx torace / HRCT (sarcoidosi).",
          "IGRA/Mantoux, sierologia sifilide, HIV (escludere infezioni).",
          "ANA (JIA), ANCA, anti-dsDNA (LES).",
          "HLA-B51 (Behçet).",
          "Angio-fluorografia, OCT se uveite posteriore.",
        ],
      },
      {
        title: "Trattamento di base",
        items: [
          "Anteriore lieve: steroidi topici (desametasone collirio) + cicloplegici.",
          "Anteriore severa/ricorrente: GC sistemici + steroid-sparing (MTX, AZA).",
          "Posteriore/panuveite: GC sistemici ± immunosoppressore.",
          "Refrattaria: anti-TNF (adalimumab è il solo biologico con indicazione approvata per uveite non infettiva).",
          "Behçet: azatioprina + GC; anti-TNF in severa; interferone-α.",
        ],
      },
    ],
  },
  {
    id: "dolore_infiammatorio",
    name: "Dolore infiammatorio vs meccanico",
    category: "Algoritmi",
    intro: "Distinguere il pattern di dolore è il primo passo per orientare la diagnosi tra artropatie infiammatorie e degenerative.",
    steps: [
      {
        title: "Dolore INFIAMMATORIO - caratteristiche",
        items: [
          "Peggiora con il riposo, migliora con il movimento.",
          "Rigidità mattutina >30-60 minuti.",
          "Dolore notturno (risveglio tipicamente nella seconda metà della notte).",
          "Tumefazione articolare calda/rossa.",
          "Rigidità dopo inattività prolungata (gelling).",
          "Risposta marcata ai FANS.",
          "Indici di flogosi elevati (VES, PCR).",
        ],
      },
      {
        title: "Dolore MECCANICO - caratteristiche",
        items: [
          "Peggiora con l'attività, migliora con il riposo.",
          "Rigidità mattutina <30 minuti.",
          "Raro dolore notturno (salvo posizioni forzate).",
          "Tumefazione assente o fredda/dura (osteofiti).",
          "Crepitii articolari, limitazione meccanica.",
          "Risposta modesta ai FANS.",
          "Indici di flogosi normali.",
        ],
      },
      {
        title: "Dolore INFIAMMATORIO CRONICO ASSIALE (ASAS-IBP)",
        items: [
          "≥4 dei seguenti 5 (sensibilità 77%, specificità 92%):",
          "1. Esordio <40 anni.",
          "2. Esordio insidioso.",
          "3. Miglioramento con l'esercizio.",
          "4. Nessun miglioramento con il riposo.",
          "5. Dolore notturno (con miglioramento all'alzarsi).",
        ],
      },
      {
        title: "Pattern articolare",
        items: [
          "Monoartrite: gotta, pseudogotta, settica, reattiva, trauma.",
          "Oligoartrite (<5): spondiloartriti, AP, sarcoidosi (Löfgren), reattiva, gotta.",
          "Poliartrite simmetrica: AR, LES, miositi, polimialgia (spalle/anche).",
          "Poliartrite asimmetrica: psoriasica, reattiva, IBD-associata.",
          "Migrante: streptococco (febbre reumatica), gonococcica, Lyme, sarcoidosi.",
          "Additiva: AR.",
          "Intermittente: gotta, FMF, palindromica, relapsing polychondritis.",
        ],
      },
    ],
  },
  {
    id: "eosinofilia",
    name: "Eosinofilia - iter diagnostico",
    category: "Algoritmi",
    intro: "Approccio sistematico all'eosinofilia periferica (>500/µL; severa >1500/µL persistente per >1 mese = ipereosinofilia). Obiettivo: distinguere forme secondarie/reattive da neoplastiche/primarie e identificare precocemente il danno d'organo eosinofilo-mediato.",
    steps: [
      {
        title: "1. Conferma e stratificazione",
        items: [
          "Confermare con 2 emocromi ripetuti a distanza di 2-4 settimane (variabilità circadiana, farmaci).",
          "Classificazione per severità: lieve 500-1500/µL, moderata 1500-5000/µL, severa >5000/µL.",
          "Ipereosinofilia: eosinofili >1500/µL persistente per >1 mese OPPURE con danno d'organo (HES - Hypereosinophilic Syndrome).",
          "Escludere pseudoeosinofilia (artefatti conta automatica) con esame morfologico su striscio.",
        ],
      },
      {
        title: "2. Anamnesi mirata",
        items: [
          "Farmaci (DRESS / reazioni farmacologiche): antibiotici (β-lattamici, sulfamidici, minociclina, vancomicina), anticonvulsivanti (carbamazepina, fenitoina, lamotrigina), allopurinolo, FANS, PPI.",
          "Viaggi ed esposizioni: paesi tropicali/subtropicali (elmintiasi), contatti con animali (toxocariasi), consumo cibi crudi (anisakidosi, trichinellosi, cisticercosi).",
          "Atopia/allergie: asma (eosinofilico vs neutrofilico), rinite, dermatite atopica, eosinofilia alimentare/esofagite eosinofila.",
          "Sintomi sistemici: calo ponderale, febbre, sudorazioni notturne (sospetto linfoma/neoplasia), dispnea (ILD, asma), porpora palpabile (EGPA), dolore addominale (gastroenterite eosinofila, EGPA mesenterica).",
          "Sintomi neurologici e cardiaci (HES con danno d'organo): neuropatia periferica, ictus, dispnea, scompenso.",
        ],
      },
      {
        title: "3. Esami di primo livello",
        items: [
          "Emocromo con formula e morfologia striscio (blasti, linfociti atipici, displasia).",
          "VES, PCR, funzione epato-renale, elettroliti, LDH, troponina I (monitoraggio cardiaco HES).",
          "IgE totali, IgG/IgA/IgM (deficit immunologici, iperIgE).",
          "Vitamina B12 e triptasi sierica (elevate in varianti neoplastiche mieloidi e mastocitosi).",
          "Esame urine, funzione tiroidea (ipoadrenalismo in Addison può associarsi a eosinofilia lieve).",
        ],
      },
      {
        title: "4. Screening parassitario",
        items: [
          "Esame parassitologico feci (3 campioni in giorni diversi).",
          "Sierologie: Strongyloides (CRUCIALE prima di GC/immunosoppressori — rischio iperinfezione), Schistosoma, Toxocara, Trichinella, Filaria, Fasciola.",
          "Se viaggio tropicale recente: striscio per filariasi, ecografia epatica per echinococcosi.",
          "Test per HIV (eosinofilia spesso associata nelle forme avanzate / infezioni opportunistiche).",
        ],
      },
      {
        title: "5. Screening autoimmune e reumatologico",
        items: [
          "ANA + ENA completi, ANCA (cANCA/pANCA e specificità MPO/PR3) — EGPA spesso pANCA+/MPO+ nel 40%.",
          "Fattore reumatoide, anti-CCP.",
          "Frazioni del complemento (C3, C4).",
          "Immunofissazione sierica/urinaria se sospetto gammapatia monoclonale / mieloma.",
          "Se sospetto EGPA: EGDS/colonscopia in base a sintomi GI, BNC/neurografia per mononeurite multipla.",
        ],
      },
      {
        title: "6. Imaging e accertamenti d'organo",
        items: [
          "RX torace + HRCT torace: infiltrati periferici a 'fotografia negativa dell'edema polmonare' (polmonite eosinofila cronica), noduli, cavitazioni (EGPA/GPA).",
          "Spirometria + DLCO + FeNO se sintomi respiratori.",
          "Ecocardiogramma + RMN cardiaca: fibrosi endomiocardica (HES cardiaco Löffler), trombi apicali, disfunzione diastolica.",
          "Ecografia addome (epatosplenomegalia in neoplasie mieloidi/sistema linfatico).",
          "TC total-body se sospetto linfoma/neoplasia solida.",
        ],
      },
      {
        title: "7. Secondo livello ematologico (se eosinofilia persistente >1500/µL senza causa)",
        items: [
          "Striscio e agoaspirato midollare + biopsia osteomidollare.",
          "Biologia molecolare: FIP1L1-PDGFRA (LPM con eosinofilia — tratta con imatinib), riarrangiamenti PDGFRB, FGFR1, PCM1-JAK2, ETV6-ABL1, BCR-ABL1.",
          "Citogenetica/FISH.",
          "Immunofenotipo linfocitario (L-HES): popolazione T aberrante CD3-/CD4+ o CD3+/CD4-/CD8- (linfoma T / sindrome HES linfocitica).",
          "Valutazione ematologica per: leucemia eosinofila cronica (CEL-NOS), neoplasie mieloidi/linfoidi con eosinofilia.",
        ],
      },
      {
        title: "8. Diagnosi differenziale principale",
        items: [
          "REATTIVE/SECONDARIE: parassitosi, atopia/asma, DRESS, gastroenterite eosinofila, ABPA, deficit B12.",
          "AUTOIMMUNI: EGPA (Churg-Strauss, ACR/EULAR 2022), IgG4-RD, fasceite eosinofila di Shulman, vasculiti.",
          "NEOPLASTICHE PRIMARIE: LPM con FIP1L1-PDGFRA, CEL-NOS, neoplasie mielo-/linfoidi associate a eosinofilia, mastocitosi sistemica.",
          "LINFOIDI: linfoma di Hodgkin e non-Hodgkin (T-cell), ATLL, LPM eosinofila linfocitica.",
          "IDIOPATICA (HES-I): diagnosi di esclusione con eosinofilia >1500/µL >6 mesi e danno d'organo.",
          "ALTRE: adrenal insufficiency, radiazioni, colesterolo-emboli, GVHD cronica.",
        ],
      },
      {
        title: "Red flags & management urgente",
        items: [
          "Eosinofilia >1500/µL + danno d'organo (cardiaco/polmonare/neurologico): hospitalizzazione e valutazione multidisciplinare (ematologo + reumatologo).",
          "Sospetto DRESS: sospensione immediata del farmaco + GC ad alte dosi; monitoraggio epatico/renale; può recrudescere a settimane di distanza.",
          "TEST STRONGYLOIDES obbligatorio prima di GC/immunosoppressori nei pazienti provenienti da aree endemiche (ivermectina preventiva se positivo o epidemiologia a rischio).",
          "Troponina + ECG + ecocardio in tutti i pazienti con eosinofilia >1500/µL persistente (sorveglianza per Löffler).",
          "Sospetto EGPA con vasculite attiva: induzione con GC ± ciclofosfamide o rituximab (ACR/EULAR 2022).",
          "FIP1L1-PDGFRA positivo: imatinib 100-400 mg/die (risposta rapida e sostenuta).",
        ],
      },
    ],
  },
];

export const MISC_GROUPS = [
  { id: "tables", label: "Tabelle di riferimento" },
  { id: "algorithms", label: "Iter diagnostici" },
];
