// Suggerimenti terapeutici per malattia reumatica
// Categories: csDMARD, bDMARD, tsDMARD, glucocorticoid, NSAID, analgesic, supportive, other

export const THERAPY_CATEGORIES = {
  csDMARD: "DMARD convenzionali",
  bDMARD: "DMARD biologici",
  tsDMARD: "DMARD targeted-synthetic",
  glucocorticoid: "Glucocorticoidi",
  NSAID: "FANS",
  analgesic: "Analgesici",
  supportive: "Sintomatica",
  other: "Altro",
};

export const THERAPY_SUGGESTIONS = [
  {
    keywords: ["artrite reumatoide", "ar ", "rheumatoid"],
    diseaseLabel: "Artrite Reumatoide",
    drugs: [
      { name: "Metotrexato (MTX)", category: "csDMARD", typical: "10-25 mg/sett" },
      { name: "Leflunomide", category: "csDMARD", typical: "20 mg/die" },
      { name: "Sulfasalazina", category: "csDMARD", typical: "2-3 g/die" },
      { name: "Idrossiclorochina", category: "csDMARD", typical: "200-400 mg/die" },
      { name: "Etanercept", category: "bDMARD", typical: "50 mg/sett s.c." },
      { name: "Adalimumab", category: "bDMARD", typical: "40 mg/2 sett s.c." },
      { name: "Infliximab", category: "bDMARD", typical: "3-5 mg/kg ogni 8 sett e.v." },
      { name: "Golimumab", category: "bDMARD", typical: "50 mg/mese s.c." },
      { name: "Certolizumab pegol", category: "bDMARD", typical: "200 mg/2 sett s.c." },
      { name: "Abatacept", category: "bDMARD", typical: "125 mg/sett s.c." },
      { name: "Tocilizumab", category: "bDMARD", typical: "162 mg/sett s.c. o 8 mg/kg/4 sett e.v." },
      { name: "Sarilumab", category: "bDMARD", typical: "200 mg/2 sett s.c." },
      { name: "Rituximab", category: "bDMARD", typical: "1 g x 2 (gg 1 e 15) ogni 6-12 mesi" },
      { name: "Tofacitinib", category: "tsDMARD", typical: "5 mg x 2/die p.o." },
      { name: "Baricitinib", category: "tsDMARD", typical: "4 mg/die p.o." },
      { name: "Upadacitinib", category: "tsDMARD", typical: "15 mg/die p.o." },
      { name: "Filgotinib", category: "tsDMARD", typical: "200 mg/die p.o." },
      { name: "Prednisone", category: "glucocorticoid", typical: "5-10 mg/die (ponte)" },
    ],
  },
  {
    keywords: ["psoriasica", "psoriasic", "artrite psor", "psa"],
    diseaseLabel: "Artrite Psoriasica",
    drugs: [
      { name: "Metotrexato", category: "csDMARD", typical: "10-25 mg/sett" },
      { name: "Leflunomide", category: "csDMARD", typical: "20 mg/die" },
      { name: "Sulfasalazina", category: "csDMARD", typical: "2 g/die" },
      { name: "Apremilast", category: "tsDMARD", typical: "30 mg x 2/die" },
      { name: "Adalimumab", category: "bDMARD", typical: "40 mg/2 sett s.c." },
      { name: "Etanercept", category: "bDMARD", typical: "50 mg/sett" },
      { name: "Infliximab", category: "bDMARD", typical: "5 mg/kg ogni 8 sett" },
      { name: "Golimumab", category: "bDMARD", typical: "50 mg/mese" },
      { name: "Certolizumab pegol", category: "bDMARD", typical: "200 mg/2 sett" },
      { name: "Secukinumab", category: "bDMARD", typical: "150-300 mg/mese (anti-IL17A)" },
      { name: "Ixekizumab", category: "bDMARD", typical: "80 mg/4 sett (anti-IL17A)" },
      { name: "Bimekizumab", category: "bDMARD", typical: "160 mg/4 sett (anti-IL17A/F)" },
      { name: "Ustekinumab", category: "bDMARD", typical: "45-90 mg/12 sett (anti-IL12/23)" },
      { name: "Guselkumab", category: "bDMARD", typical: "100 mg/8 sett (anti-IL23)" },
      { name: "Risankizumab", category: "bDMARD", typical: "150 mg/12 sett (anti-IL23)" },
      { name: "Tofacitinib", category: "tsDMARD", typical: "5 mg x 2/die" },
      { name: "Upadacitinib", category: "tsDMARD", typical: "15 mg/die" },
    ],
  },
  {
    keywords: ["spondilo", "axspa", "anchilosante", "spa "],
    diseaseLabel: "Spondiloartrite",
    drugs: [
      { name: "Naprossene", category: "NSAID", typical: "500-1000 mg/die" },
      { name: "Ibuprofene", category: "NSAID", typical: "1200-2400 mg/die" },
      { name: "Etoricoxib", category: "NSAID", typical: "60-90 mg/die" },
      { name: "Adalimumab", category: "bDMARD", typical: "40 mg/2 sett s.c." },
      { name: "Etanercept", category: "bDMARD", typical: "50 mg/sett" },
      { name: "Infliximab", category: "bDMARD", typical: "5 mg/kg ogni 6-8 sett" },
      { name: "Golimumab", category: "bDMARD", typical: "50 mg/mese" },
      { name: "Certolizumab pegol", category: "bDMARD", typical: "200 mg/2 sett" },
      { name: "Secukinumab", category: "bDMARD", typical: "150 mg/mese" },
      { name: "Ixekizumab", category: "bDMARD", typical: "80 mg/4 sett" },
      { name: "Bimekizumab", category: "bDMARD", typical: "160 mg/4 sett" },
      { name: "Tofacitinib", category: "tsDMARD", typical: "5 mg x 2/die" },
      { name: "Upadacitinib", category: "tsDMARD", typical: "15 mg/die" },
      { name: "Sulfasalazina", category: "csDMARD", typical: "2 g/die (forme periferiche)" },
    ],
  },
  {
    keywords: ["lupus", "les", "sle "],
    diseaseLabel: "LES",
    drugs: [
      { name: "Idrossiclorochina", category: "csDMARD", typical: "5 mg/kg/die (max 400 mg)" },
      { name: "Prednisone", category: "glucocorticoid", typical: "5-60 mg/die (in base alla gravità)" },
      { name: "Metilprednisolone (boli)", category: "glucocorticoid", typical: "500-1000 mg/die x 3 (severità)" },
      { name: "Micofenolato mofetil (MMF)", category: "csDMARD", typical: "2-3 g/die" },
      { name: "Azatioprina", category: "csDMARD", typical: "1-2.5 mg/kg/die" },
      { name: "Metotrexato", category: "csDMARD", typical: "10-25 mg/sett" },
      { name: "Ciclofosfamide", category: "csDMARD", typical: "EuroLupus / NIH" },
      { name: "Belimumab", category: "bDMARD", typical: "10 mg/kg ogni 4 sett e.v. o 200 mg/sett s.c." },
      { name: "Anifrolumab", category: "bDMARD", typical: "300 mg ogni 4 sett e.v." },
      { name: "Rituximab", category: "bDMARD", typical: "off-label" },
      { name: "Voclosporina", category: "csDMARD", typical: "23.7 mg x 2/die (LN)" },
    ],
  },
  {
    keywords: ["sjogren", "sjögren"],
    diseaseLabel: "Sjögren",
    drugs: [
      { name: "Pilocarpina", category: "supportive", typical: "5 mg x 4/die (xerostomia)" },
      { name: "Cevimelina", category: "supportive", typical: "30 mg x 3/die" },
      { name: "Lacrime artificiali", category: "supportive", typical: "Al bisogno" },
      { name: "Idrossiclorochina", category: "csDMARD", typical: "200-400 mg/die" },
      { name: "Metotrexato", category: "csDMARD", typical: "10-15 mg/sett (artralgie)" },
      { name: "Rituximab", category: "bDMARD", typical: "1 g x 2 (forme severe)" },
      { name: "Prednisone", category: "glucocorticoid", typical: "5-30 mg/die" },
    ],
  },
  {
    keywords: ["vasculit", "anca", "gpa", "mpa", "egpa"],
    diseaseLabel: "Vasculiti ANCA",
    drugs: [
      { name: "Rituximab (induzione)", category: "bDMARD", typical: "375 mg/m² x 4 sett o 1 g x 2" },
      { name: "Ciclofosfamide (induzione)", category: "csDMARD", typical: "EUVAS o NIH" },
      { name: "Metilprednisolone (boli)", category: "glucocorticoid", typical: "500-1000 mg x 3 gg" },
      { name: "Prednisone", category: "glucocorticoid", typical: "1 mg/kg/die a scalare" },
      { name: "Avacopan", category: "tsDMARD", typical: "30 mg x 2/die p.o." },
      { name: "Rituximab (mantenimento)", category: "bDMARD", typical: "500 mg/6 mesi" },
      { name: "Azatioprina (mantenimento)", category: "csDMARD", typical: "1.5-2 mg/kg/die" },
      { name: "Metotrexato (mantenimento)", category: "csDMARD", typical: "20-25 mg/sett" },
      { name: "Mepolizumab (EGPA)", category: "bDMARD", typical: "300 mg/mese s.c." },
    ],
  },
  {
    keywords: ["miosit", "polimiosit", "dermatomiosit"],
    diseaseLabel: "Miositi infiammatorie",
    drugs: [
      { name: "Prednisone", category: "glucocorticoid", typical: "1 mg/kg/die" },
      { name: "Metilprednisolone (boli)", category: "glucocorticoid", typical: "1 g x 3 gg (severità)" },
      { name: "Metotrexato", category: "csDMARD", typical: "15-25 mg/sett" },
      { name: "Azatioprina", category: "csDMARD", typical: "1.5-2.5 mg/kg/die" },
      { name: "Micofenolato mofetil", category: "csDMARD", typical: "2-3 g/die" },
      { name: "Rituximab", category: "bDMARD", typical: "1 g x 2 ogni 6 mesi" },
      { name: "IVIg", category: "supportive", typical: "2 g/kg/mese" },
      { name: "Tacrolimus", category: "csDMARD", typical: "ILD" },
    ],
  },
  {
    keywords: ["fibromialg"],
    diseaseLabel: "Fibromialgia",
    drugs: [
      { name: "Amitriptilina", category: "analgesic", typical: "10-50 mg sera" },
      { name: "Duloxetina", category: "analgesic", typical: "30-60 mg/die" },
      { name: "Pregabalin", category: "analgesic", typical: "150-450 mg/die" },
      { name: "Gabapentin", category: "analgesic", typical: "900-2400 mg/die" },
      { name: "Tramadolo", category: "analgesic", typical: "50-200 mg/die" },
      { name: "Esercizio aerobico graduato", category: "supportive", typical: "Programma fisioterapico" },
    ],
  },
  {
    keywords: ["sclerosi sistem", "sclerodermia", "ssc ", "scleroderma", "vedoss"],
    diseaseLabel: "Sclerosi Sistemica",
    drugs: [
      { name: "Idrossiclorochina", category: "csDMARD", typical: "200-400 mg/die (artralgie)" },
      { name: "Metotrexato", category: "csDMARD", typical: "15-25 mg/sett (skin)" },
      { name: "Micofenolato mofetil", category: "csDMARD", typical: "2-3 g/die (skin/ILD)" },
      { name: "Ciclofosfamide", category: "csDMARD", typical: "ILD severa" },
      { name: "Tocilizumab", category: "bDMARD", typical: "162 mg/sett s.c. (skin/ILD)" },
      { name: "Rituximab", category: "bDMARD", typical: "1 g x 2 (skin/ILD)" },
      { name: "Nintedanib", category: "tsDMARD", typical: "150 mg x 2/die (ILD progressiva)" },
      { name: "Bosentan", category: "tsDMARD", typical: "62.5-125 mg x 2/die (ulcere/PAH)" },
      { name: "Macitentan", category: "tsDMARD", typical: "10 mg/die (PAH)" },
      { name: "Sildenafil", category: "tsDMARD", typical: "20 mg x 3/die (Raynaud/PAH)" },
      { name: "Iloprost", category: "supportive", typical: "Cicli e.v. 5 gg/mese (Raynaud)" },
      { name: "Nifedipina", category: "supportive", typical: "30-60 mg/die (Raynaud)" },
    ],
  },
  {
    keywords: ["gotta", "gout"],
    diseaseLabel: "Gotta",
    drugs: [
      { name: "Allopurinolo", category: "csDMARD", typical: "100-300 mg/die (titolare)" },
      { name: "Febuxostat", category: "csDMARD", typical: "80-120 mg/die" },
      { name: "Pegloticasi", category: "bDMARD", typical: "8 mg ogni 2 sett (refrattaria)" },
      { name: "Colchicina", category: "supportive", typical: "0.5 mg x 2/die (profilassi e attacco)" },
      { name: "Indometacina/Naproxene", category: "NSAID", typical: "Attacco acuto" },
      { name: "Prednisone", category: "glucocorticoid", typical: "30-40 mg x 5 gg (attacco)" },
    ],
  },
  {
    keywords: ["polimialgia", "pmr"],
    diseaseLabel: "Polimialgia Reumatica",
    drugs: [
      { name: "Prednisone", category: "glucocorticoid", typical: "12.5-25 mg/die (riduzione lenta)" },
      { name: "Metotrexato", category: "csDMARD", typical: "10-15 mg/sett (steroid-sparing)" },
      { name: "Tocilizumab", category: "bDMARD", typical: "PMR refrattaria" },
    ],
  },
  {
    keywords: ["behçet", "behcet"],
    diseaseLabel: "Malattia di Behçet",
    drugs: [
      { name: "Colchicina", category: "supportive", typical: "1-2 mg/die (mucocutanee)" },
      { name: "Prednisone", category: "glucocorticoid", typical: "0.5-1 mg/kg/die" },
      { name: "Azatioprina", category: "csDMARD", typical: "2.5 mg/kg/die" },
      { name: "Ciclosporina", category: "csDMARD", typical: "Coinvolgimento oculare" },
      { name: "Adalimumab", category: "bDMARD", typical: "Forme refrattarie" },
      { name: "Infliximab", category: "bDMARD", typical: "Coinvolgimento oculare/SNC" },
      { name: "Apremilast", category: "tsDMARD", typical: "Ulcere orali" },
      { name: "IFN-α", category: "bDMARD", typical: "Uveite refrattaria" },
    ],
  },
  {
    keywords: ["igg4", "igg-4"],
    diseaseLabel: "IgG4-RD",
    drugs: [
      { name: "Prednisone", category: "glucocorticoid", typical: "0.6 mg/kg/die" },
      { name: "Rituximab", category: "bDMARD", typical: "1 g x 2 (refrattaria/recidiva)" },
      { name: "Azatioprina", category: "csDMARD", typical: "Mantenimento" },
      { name: "Micofenolato mofetil", category: "csDMARD", typical: "Mantenimento" },
    ],
  },
];

export function suggestTherapiesForDiagnosis(diagnosis) {
  if (!diagnosis) return [];
  const text = String(diagnosis).toLowerCase();
  return THERAPY_SUGGESTIONS.filter((g) => g.keywords.some((k) => text.includes(k.toLowerCase())));
}
